#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q04.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
cargo(){ command "${CARGO:-cargo}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
cargo --version >/dev/null 2>&1 || invalid "no working cargo ($CARGO=${CARGO:-cargo})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: the char-scanning original silently drops the '-' sign.
# A correct rewrite parses whole tokens, so negatives and surrounding whitespace
# both survive; empty tokens are skipped.
mkdir -p tests
cat > tests/hidden_gate.rs <<'RS'
use q04::parse_int_list;
#[test] fn positives() { assert_eq!(parse_int_list("1,2,3"), vec![1,2,3]); }
#[test] fn negatives_from_example() { assert_eq!(parse_int_list("3, -1, 42"), vec![3,-1,42]); }
#[test] fn whitespace_padded() { assert_eq!(parse_int_list("  10 ,   20  "), vec![10,20]); }
#[test] fn all_negative() { assert_eq!(parse_int_list("-5,-6,-7"), vec![-5,-6,-7]); }
#[test] fn empty_input() { assert_eq!(parse_int_list(""), Vec::<i64>::new()); }
RS

out=$(cargo test --test hidden_gate --quiet 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'panicked|assertion|error\[|FAILED' | head -4 | tr '\n' ' ')"
fi
echo "$out" | grep -qE 'test result: ok' \
  && pass "all 5 hidden parse_int_list tests passed" \
  || fail "no green result: $(echo "$out" | tail -3 | tr '\n' ' ')"
