#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q12.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
cargo(){ command "${CARGO:-cargo}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
cargo --version >/dev/null 2>&1 || invalid "no working cargo ($CARGO=${CARGO:-cargo})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: correctness at the window boundaries (k==0, exactly-k,
# just-over-k, adjacent), PLUS a large all-distinct input with a big k that only
# a roughly-linear implementation can finish quickly. The naive O(n*k) fixture
# takes many seconds; an O(n) sliding-window/set approach is well under a second.
mkdir -p tests
cat > tests/hidden_gate.rs <<'RS'
use q12::has_duplicate_within_k;
#[test] fn k_zero_never_matches() { assert!(!has_duplicate_within_k(&[1, 1], 0)); }
#[test] fn exactly_k_apart() { assert!(has_duplicate_within_k(&[1, 2, 3, 1], 3)); }
#[test] fn just_over_k() { assert!(!has_duplicate_within_k(&[1, 2, 3, 1], 2)); }
#[test] fn adjacent() { assert!(has_duplicate_within_k(&[5, 5], 1)); }
#[test] fn no_duplicates() { assert!(!has_duplicate_within_k(&[1, 2, 3, 4], 10)); }
#[test]
fn large_input_must_be_fast() {
    let n = 200_000usize;
    let data: Vec<i64> = (0..n as i64).collect(); // all distinct -> false, forces a full scan
    let start = std::time::Instant::now();
    let got = has_duplicate_within_k(&data, 100_000);
    let elapsed = start.elapsed();
    assert!(!got);
    assert!(
        elapsed.as_secs_f64() < 2.5,
        "too slow ({elapsed:?}); needs a roughly-linear approach"
    );
}
RS

out=$(cargo test --release --test hidden_gate --quiet 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'panicked|too slow|assertion|error\[|FAILED' | head -4 | tr '\n' ' ')"
fi
echo "$out" | grep -qE 'test result: ok' \
  && pass "correct and fast on large input" \
  || fail "no green result: $(echo "$out" | tail -3 | tr '\n' ' ')"
