#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q10.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
cargo(){ command "${CARGO:-cargo}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
cargo --version >/dev/null 2>&1 || invalid "no working cargo ($CARGO=${CARGO:-cargo})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: octet range (>255), leading zeros (non-canonical),
# wrong octet count, empty octets, non-digits, and surrounding whitespace.
mkdir -p tests
cat > tests/hidden_gate.rs <<'RS'
use q10::is_valid_ipv4;
#[test] fn valid_addresses() {
    assert!(is_valid_ipv4("192.168.0.1"));
    assert!(is_valid_ipv4("0.0.0.0"));
    assert!(is_valid_ipv4("255.255.255.255"));
}
#[test] fn octet_out_of_range() { assert!(!is_valid_ipv4("256.1.1.1")); assert!(!is_valid_ipv4("1.2.3.300")); }
#[test] fn leading_zeros_rejected() { assert!(!is_valid_ipv4("01.2.3.4")); assert!(!is_valid_ipv4("1.2.3.04")); }
#[test] fn zero_octet_ok() { assert!(is_valid_ipv4("10.0.0.1")); }
#[test] fn wrong_octet_count() { assert!(!is_valid_ipv4("1.2.3")); assert!(!is_valid_ipv4("1.2.3.4.5")); }
#[test] fn empty_octet() { assert!(!is_valid_ipv4("1.2.3.")); assert!(!is_valid_ipv4("1..3.4")); }
#[test] fn non_digits_and_space() { assert!(!is_valid_ipv4("1.2.3.a")); assert!(!is_valid_ipv4(" 1.2.3.4")); assert!(!is_valid_ipv4("1.2.3.4 ")); }
RS

out=$(cargo test --test hidden_gate --quiet 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'panicked|assertion|error\[|FAILED' | head -4 | tr '\n' ' ')"
fi
echo "$out" | grep -qE 'test result: ok' \
  && pass "all hidden ipv4 tests passed" \
  || fail "no green result: $(echo "$out" | tail -3 | tr '\n' ' ')"
