#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q26.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
node(){ command "${NODE:-node}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
node -e '' >/dev/null 2>&1 || invalid "no working node ($NODE=${NODE:-node})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: key-order independence, NaN==NaN but NaN!=null, an
# undefined property vs a missing one, nested structures, array/object distinction.
cat > hidden_gate.mjs <<'JS'
import assert from "node:assert/strict";
import { deepEqual } from "./solution.mjs";

assert.strictEqual(deepEqual({ a: 1, b: 2 }, { b: 2, a: 1 }), true, "key order");
assert.strictEqual(deepEqual({ x: { y: [1, 2] } }, { x: { y: [1, 2] } }), true, "nested");
assert.strictEqual(deepEqual(NaN, NaN), true, "NaN equals NaN");
assert.strictEqual(deepEqual(NaN, null), false, "NaN vs null");
assert.strictEqual(deepEqual({ a: undefined }, {}), false, "undefined prop vs missing");
assert.strictEqual(deepEqual({ a: 1 }, { a: 2 }), false, "different values");
assert.strictEqual(deepEqual([1, 2], [1, 2, 3]), false, "different length");
assert.strictEqual(deepEqual([], {}), false, "array vs object");
assert.strictEqual(deepEqual({ a: 1 }, { a: 1, b: 2 }), false, "extra key");
console.log("OK");
JS

out=$(node hidden_gate.mjs 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'AssertionError|Error|order|NaN|prop' | head -4 | tr '\n' ' ')"
fi
pass "all hidden deepEqual tests passed"
