#!/usr/bin/env bash
# Rewritten from ABCC's `validation` string for task `node_note_handlers`
# (scripts/ultimate-100-task-test.js, agent-battle-command-center @ d5528ea).
#
# Generated by harness/crates/w8-import. Every edit to the donor is recorded in this
# task's task.toml [provenance].caveats; the assertion body below is NOT edited.
#
# SPEC.md §8: invoked as `bash verify.sh <workdir> <transcript>`, writes exactly one
# RESULT: line to stdout, exit status ignored, both arguments absolute. Output with no
# RESULT: line is INVALID, never FAIL — "the verifier did not run" and "the artifact is
# wrong" are different facts and the donor conflated them (F8).
set -u

work="${1:?usage: verify.sh <workdir> <transcript>}"
: "${2-}"   # transcript, unused: this donor verifier reads only the artifact

interp="${NODE:-node}"

# SPEC §8: probe by EXECUTING, not by looking.
# An interpreter that resolves but does not run is the failure this catches.
# A mis-resolved interpreter is INVALID, never FAIL.
if ! "$interp" -e '' >/dev/null 2>&1; then
  echo "RESULT: INVALID interpreter '$interp' does not execute"
  exit 0
fi

cd "$work" || { echo "RESULT: INVALID workdir '$work' does not exist"; exit 0; }

# The donor scores `exit 0 AND "PASS" in stdout` (ultimate-100-task-test.js:2809 and
# packages/agents/src/main.py:524-589). That contract is reproduced here rather than
# replaced: these verifiers reject by calling process.exit(1) rather than by throwing,
# so an in-process try/catch would not see a rejection at all.
out="$("$interp" - <<'JS' 2>&1
var NoteStore=require('./noteModel'); var h=require('./noteHandlers'); var s=new NoteStore(); var r=h.handleCreate(s,'{"title":"test"}'); if(r.status!==201) process.exit(1); var d=JSON.parse(r.body); var r2=h.handleList(s); if(r2.status!==200) process.exit(1); var r3=h.handleGet(s,d.id); if(r3.status!==200) process.exit(1); var r4=h.handleDelete(s,d.id); if(r4.status!==200) process.exit(1); var r5=h.handleGet(s,d.id); if(r5.status!==404) process.exit(1); console.log('PASS')
JS
)"
rc=$?

if [ "$rc" -eq 0 ] && printf '%s\n' "$out" | grep -q '^PASS$'; then
  echo "RESULT: PASS donor assertions held"
  exit 0
fi

# The FIRST error line, not the last: node prints the error near the top and closes with
# a `Node.js vX` banner, so taking the last line reports a version string as the reason.
# The optional dotted prefix and the empty stem both matter — a bare `Error:` line is
# how node reports a missing module, and requiring a character before `Error` misses it.
detail="$(printf '%s\n' "$out" \
  | grep -m1 -E '^([A-Za-z_][A-Za-z0-9_.]*\.)?[A-Za-z_]*(Error|Exception)\b')"
if [ -z "$detail" ]; then
  if [ "$rc" -ne 0 ]; then
    detail="exit $rc, no error line (the donor verifier's process.exit reject path)"
  else
    detail="no PASS on stdout"
  fi
fi
echo "RESULT: FAIL $detail"
