#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q55.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
node(){ command "${NODE:-node}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
node -e '' >/dev/null 2>&1 || invalid "no working node ($NODE=${NODE:-node})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests (trap-dense): overlap merge, TOUCHING merge (endpoint),
# unsorted input, fully-contained interval, disjoint set sorted, empty, single.
cat > hidden_gate.ts <<'TS'
import assert from "node:assert/strict";
import { mergeIntervals } from "./solution.ts";

assert.deepEqual(mergeIntervals([[1, 3], [2, 4]]), [[1, 4]], "overlap");
assert.deepEqual(mergeIntervals([[1, 2], [2, 3]]), [[1, 3]], "touching merges");
assert.deepEqual(mergeIntervals([[3, 4], [1, 2]]), [[1, 2], [3, 4]], "unsorted input");
assert.deepEqual(mergeIntervals([[1, 5], [2, 3]]), [[1, 5]], "contained");
assert.deepEqual(mergeIntervals([[1, 2], [5, 6], [3, 4]]), [[1, 2], [3, 4], [5, 6]], "disjoint sorted");
assert.deepEqual(mergeIntervals([]), [], "empty");
assert.deepEqual(mergeIntervals([[7, 9]]), [[7, 9]], "single");
console.log("OK");
TS

out=$(node hidden_gate.ts 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'AssertionError|Error|touching|unsorted' | head -4 | tr '\n' ' ')"
fi
pass "all hidden mergeIntervals tests passed"
