#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q36.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
node(){ command "${NODE:-node}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
node -e '' >/dev/null 2>&1 || invalid "no working node ($NODE=${NODE:-node})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: nested objects and arrays must be independent after clone.
cat > hidden_gate.ts <<'TS'
import assert from "node:assert/strict";
import { deepClone } from "./solution.ts";

const obj = { a: { b: 1 } };
const c1 = deepClone(obj);
c1.a.b = 99;
assert.strictEqual(obj.a.b, 1, "nested object independence");

const arr = [[1, 2]];
const c2 = deepClone(arr);
c2[0][0] = 99;
assert.strictEqual(arr[0][0], 1, "nested array independence");

assert.deepEqual(deepClone({ x: { y: [1, 2] } }), { x: { y: [1, 2] } }, "equal values");
assert.strictEqual(deepClone(5), 5, "primitive number");
assert.strictEqual(deepClone("s"), "s", "primitive string");

// array of objects: each cloned object must be independent
const aoo = [{ n: 1 }, { n: 2 }];
const caoo = deepClone(aoo);
caoo[0].n = 99;
assert.strictEqual(aoo[0].n, 1, "array-of-objects element independence");
console.log("OK");
TS

out=$(node hidden_gate.ts 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'AssertionError|Error|independence' | head -4 | tr '\n' ' ')"
fi
pass "all hidden deepClone tests passed"
