#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q05.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
cargo(){ command "${CARGO:-cargo}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
cargo --version >/dev/null 2>&1 || invalid "no working cargo ($CARGO=${CARGO:-cargo})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: signature must become Result, malformed lines -> Err,
# and the subtle edge — blank/whitespace-only lines are SKIPPED, not treated as
# malformed (a naive `split_once('=').ok_or(..)?` per line would wrongly error).
mkdir -p tests
cat > tests/hidden_gate.rs <<'RS'
use q05::parse_kv;
use std::collections::HashMap;
fn m(pairs: &[(&str, &str)]) -> HashMap<String, String> {
    pairs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect()
}
#[test] fn basic_ok() { assert_eq!(parse_kv("a=1\nb=2"), Ok(m(&[("a","1"),("b","2")]))); }
#[test] fn trims_whitespace() { assert_eq!(parse_kv("  x  =  hello "), Ok(m(&[("x","hello")]))); }
#[test] fn blank_lines_skipped() { assert_eq!(parse_kv("a=1\n\n   \nb=2"), Ok(m(&[("a","1"),("b","2")]))); }
#[test] fn malformed_is_err() { assert!(parse_kv("a=1\nnope").is_err()); }
#[test] fn empty_value_ok() { assert_eq!(parse_kv("k="), Ok(m(&[("k","")]))); }
RS

out=$(cargo test --test hidden_gate --quiet 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'panicked|assertion|error\[|mismatched|FAILED' | head -4 | tr '\n' ' ')"
fi
echo "$out" | grep -qE 'test result: ok' \
  && pass "all 5 hidden parse_kv tests passed" \
  || fail "no green result: $(echo "$out" | tail -3 | tr '\n' ' ')"
