#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q45.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer test: drop full-line comments (indented or not) and blank/whitespace
# lines; keep code lines including ones with a trailing inline '#'.
input='code1
    # indented comment
# comment


code2  # not a stripped comment'
expected='code1
code2  # not a stripped comment'

got=$(printf '%s' "$input" | bash solution.sh 2>/dev/null)
[ "$got" = "$expected" ] || fail "expected [$expected] got [$got]"
pass "comments and blank lines stripped, inline # kept"
