#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q06.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
cargo(){ command "${CARGO:-cargo}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
cargo --version >/dev/null 2>&1 || invalid "no working cargo ($CARGO=${CARGO:-cargo})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: the subtractive forms (IV, IX, XL, XC, CD, CM) and the
# range boundaries a naive additive implementation gets wrong.
mkdir -p tests
cat > tests/hidden_gate.rs <<'RS'
use q06::int_to_roman;
#[test] fn one() { assert_eq!(int_to_roman(1), "I"); }
#[test] fn four_ix() { assert_eq!(int_to_roman(4), "IV"); assert_eq!(int_to_roman(9), "IX"); }
#[test] fn fifty_eight() { assert_eq!(int_to_roman(58), "LVIII"); }
#[test] fn forty_ninety() { assert_eq!(int_to_roman(40), "XL"); assert_eq!(int_to_roman(90), "XC"); }
#[test] fn four_nine_hundred() { assert_eq!(int_to_roman(400), "CD"); assert_eq!(int_to_roman(900), "CM"); }
#[test] fn year_1994() { assert_eq!(int_to_roman(1994), "MCMXCIV"); }
#[test] fn max_3999() { assert_eq!(int_to_roman(3999), "MMMCMXCIX"); }
RS

out=$(cargo test --test hidden_gate --quiet 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'panicked|assertion|error\[|FAILED' | head -4 | tr '\n' ' ')"
fi
echo "$out" | grep -qE 'test result: ok' \
  && pass "all hidden int_to_roman tests passed" \
  || fail "no green result: $(echo "$out" | tail -3 | tr '\n' ' ')"
