"""Build a runnable BCF scorer WITHOUT porting it.

`rule_score` and `detect_language_hint` are extracted VERBATIM from the donor's
`src/router.rs` by byte range and written into a throwaway crate.  The extracted
text is asserted to be a byte-for-byte slice of the donor file, so the thing that
runs is the donor's code and not a transcription of it.  Nothing else from
router.rs is taken: the rest needs `LlmClient`, and the AI half of the dual
assessment is not what this measures.
"""
import hashlib
import os
import re

DONOR = r"D:\dev\battle-command-forge\src\router.rs"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "bcf_score")


def extract(src: str, sig: str) -> str:
    i = src.index(sig)
    # walk braces from the first '{' after the signature
    j = src.index("{", i)
    depth = 0
    k = j
    while k < len(src):
        if src[k] == "{":
            depth += 1
        elif src[k] == "}":
            depth -= 1
            if depth == 0:
                return src[i:k + 1]
        k += 1
    raise RuntimeError("unbalanced braces for " + sig)


def main():
    src = open(DONOR, encoding="utf-8").read()
    sha = hashlib.sha256(src.encode("utf-8")).hexdigest()
    rule = extract(src, "fn rule_score(prompt: &str) -> u32")
    lang = extract(src, "fn detect_language_hint(lower: &str) -> &str")
    assert rule in src and lang in src, "extraction is not a verbatim slice"
    print(f"donor router.rs sha256 = {sha}")
    print(f"rule_score            = {len(rule)} bytes, "
          f"{src[:src.index(rule)].count(chr(10)) + 1}.."
          f"{src[:src.index(rule) + len(rule)].count(chr(10)) + 1}")
    print(f"detect_language_hint  = {len(lang)} bytes, "
          f"{src[:src.index(lang)].count(chr(10)) + 1}.."
          f"{src[:src.index(lang) + len(lang)].count(chr(10)) + 1}")

    os.makedirs(os.path.join(OUT, "src"), exist_ok=True)
    with open(os.path.join(OUT, "Cargo.toml"), "w", encoding="utf-8", newline="\n") as f:
        f.write(
            "[package]\nname = \"bcf_score\"\nversion = \"0.0.0\"\nedition = \"2021\"\n"
            "\n[workspace]\n\n[dependencies]\n"
        )
    body = [
        "// GENERATED by build_bcf_scorer.py. Do not edit.",
        f"// rule_score / detect_language_hint are a VERBATIM byte slice of",
        f"// {DONOR}  (sha256 {sha}).",
        "use std::io::Read;",
        "",
        rule,
        "",
        lang,
        "",
        "fn main() {",
        "    let mut s = String::new();",
        "    std::io::stdin().read_to_string(&mut s).unwrap();",
        "    // stdin is one prompt per record, records separated by a NUL byte.",
        "    for rec in s.split('\\u{0}') {",
        "        if rec.is_empty() { continue; }",
        "        let (id, text) = rec.split_once('\\u{1}').unwrap_or((\"?\", rec));",
        "        println!(\"{}\\t{}\", id, rule_score(text));",
        "    }",
        "}",
    ]
    with open(os.path.join(OUT, "src", "main.rs"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(body) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
