#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q37.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
node(){ command "${NODE:-node}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
node -e '' >/dev/null 2>&1 || invalid "no working node ($NODE=${NODE:-node})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: descending ranges with negative steps, plus ascending,
# non-dividing, and equal-endpoint cases must all stay correct (end exclusive).
cat > hidden_gate.ts <<'TS'
import assert from "node:assert/strict";
import { range } from "./solution.ts";

assert.deepEqual(range(0, 5), [0, 1, 2, 3, 4], "ascending");
assert.deepEqual(range(0, 10, 2), [0, 2, 4, 6, 8], "step 2");
assert.deepEqual(range(5, 0, -1), [5, 4, 3, 2, 1], "descending");
assert.deepEqual(range(10, 0, -2), [10, 8, 6, 4, 2], "descending step 2");
assert.deepEqual(range(0, 5, 2), [0, 2, 4], "non-dividing stops before end");
assert.deepEqual(range(3, 3), [], "equal endpoints");
assert.deepEqual(range(0, 5, 0), [], "zero step -> empty (no infinite loop)");
console.log("OK");
TS

out=$(node hidden_gate.ts 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'AssertionError|Error' | head -4 | tr '\n' ' ')"
fi
pass "all hidden range tests passed"
