#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q15.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
pytest(){ command "${PYTEST:-pytest}" "$@"; }
python(){ command "${PYTHON:-python}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
pytest --version >/dev/null 2>&1 || invalid "no working pytest ($PYTEST=${PYTEST:-pytest})"
python --version >/dev/null 2>&1 || invalid "no working python ($PYTHON=${PYTHON:-python})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: return + call-once on success; retry-then-succeed with
# the right call count; and on total failure re-raise the LAST exception (not None).
cat > hidden_gate_test.py <<'PY'
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pytest
from solution import retry

def test_returns_on_first_success():
    calls = {"n": 0}
    def f():
        calls["n"] += 1
        return 42
    assert retry(f, 3) == 42
    assert calls["n"] == 1

def test_retries_then_succeeds():
    calls = {"n": 0}
    def f():
        calls["n"] += 1
        if calls["n"] < 3:
            raise RuntimeError("not yet")
        return "ok"
    assert retry(f, 5) == "ok"
    assert calls["n"] == 3

def test_reraises_last_exception():
    calls = {"n": 0}
    def f():
        calls["n"] += 1
        raise ValueError(f"boom {calls['n']}")
    with pytest.raises(ValueError) as excinfo:
        retry(f, 3)
    assert "boom 3" in str(excinfo.value)
    assert calls["n"] == 3

def test_single_attempt_reraises():
    calls = {"n": 0}
    def f():
        calls["n"] += 1
        raise KeyError("once")
    with pytest.raises(KeyError):
        retry(f, 1)
    assert calls["n"] == 1
PY

out=$(python -m pytest -q hidden_gate_test.py 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'assert|error|failed|raise' | head -4 | tr '\n' ' ')"
fi
pass "all hidden retry tests passed"
