#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q29.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
node(){ command "${NODE:-node}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
node -e '' >/dev/null 2>&1 || invalid "no working node ($NODE=${NODE:-node})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: deep hit, missing path -> default (no throw), traversal
# through null -> default, array indices, and a present falsy value returned.
cat > hidden_gate.mjs <<'JS'
import assert from "node:assert/strict";
import { safeGet } from "./solution.mjs";

assert.strictEqual(safeGet({ a: { b: { c: 1 } } }, "a.b.c"), 1, "deep hit");
assert.strictEqual(safeGet({ a: 1 }, "x.y.z", "def"), "def", "missing path");
assert.strictEqual(safeGet({ a: null }, "a.b", "d"), "d", "through null");
assert.strictEqual(safeGet({ a: [{ b: 5 }] }, "a.0.b"), 5, "array index");
assert.strictEqual(safeGet({ a: { b: 0 } }, "a.b", "def"), 0, "present falsy kept");
assert.strictEqual(safeGet({ a: 1 }, "a.b", "d"), "d", "past a primitive");
assert.strictEqual(safeGet(null, "a.b", "d"), "d", "null root -> default");
console.log("OK");
JS

out=$(node hidden_gate.mjs 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'AssertionError|TypeError|Error' | head -4 | tr '\n' ' ')"
fi
pass "all hidden safeGet tests passed"
