#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q40.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
node(){ command "${NODE:-node}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
node -e '' >/dev/null 2>&1 || invalid "no working node ($NODE=${NODE:-node})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: args passed through; multiple listeners fire in order; off
# removes a specific listener; once fires exactly once; unknown event is a no-op.
cat > hidden_gate.ts <<'TS'
import assert from "node:assert/strict";
import { EventEmitter } from "./solution.ts";

// args + single listener
const a = new EventEmitter();
let got: unknown[] = [];
a.on("e", (...args) => { got = args; });
a.emit("e", 1, "x");
assert.deepEqual(got, [1, "x"], "args passed through");

// multiple listeners in registration order
const b = new EventEmitter();
const order: number[] = [];
b.on("e", () => order.push(1));
b.on("e", () => order.push(2));
b.emit("e");
assert.deepEqual(order, [1, 2], "listeners fire in order");

// off removes a specific listener
const c = new EventEmitter();
let n = 0;
const inc = () => { n += 1; };
c.on("e", inc);
c.off("e", inc);
c.emit("e");
assert.strictEqual(n, 0, "off removes listener");

// once fires exactly once
const d = new EventEmitter();
let m = 0;
d.once("e", () => { m += 1; });
d.emit("e");
d.emit("e");
assert.strictEqual(m, 1, "once fires once");

// unknown event is a no-op (must not throw)
const f = new EventEmitter();
f.emit("nothing");

// the same listener registered twice fires twice
const g = new EventEmitter();
let twice = 0;
const bump = () => { twice += 1; };
g.on("e", bump);
g.on("e", bump);
g.emit("e");
assert.strictEqual(twice, 2, "same listener added twice fires twice");
console.log("OK");
TS

out=$(node hidden_gate.ts 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'AssertionError|Error|once|order' | head -4 | tr '\n' ' ')"
fi
pass "all hidden EventEmitter tests passed"
