#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q01.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
cargo(){ command "${CARGO:-cargo}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
cargo --version >/dev/null 2>&1 || invalid "no working cargo ($CARGO=${CARGO:-cargo})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: the prompt states the goal ("clean slugs for whatever
# titles people throw at it") and shows one example; these grade the edges that
# implies but does not spell out — punctuation stripping, run collapsing, edge
# trimming, and the all-punctuation empty case.
mkdir -p tests
cat > tests/hidden_gate.rs <<'RS'
use q01::slugify;
#[test] fn example_from_prompt() { assert_eq!(slugify("My First Post!"), "my-first-post"); }
#[test] fn collapse_separator_runs() { assert_eq!(slugify("a  --  b"), "a-b"); }
#[test] fn trim_and_strip_punct() { assert_eq!(slugify("  Hello, World!  "), "hello-world"); }
#[test] fn digits_preserved() { assert_eq!(slugify("Rust 101 Rocks"), "rust-101-rocks"); }
#[test] fn all_punctuation_is_empty() { assert_eq!(slugify("!!! ??? ..."), ""); }
#[test] fn already_a_slug_is_stable() { assert_eq!(slugify("already-a-slug"), "already-a-slug"); }
RS

out=$(cargo test --test hidden_gate --quiet 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'panicked|assertion|error\[|FAILED' | head -4 | tr '\n' ' ')"
fi
echo "$out" | grep -qE 'test result: ok' \
  && pass "all 6 hidden slug tests passed" \
  || fail "no green result: $(echo "$out" | tail -3 | tr '\n' ' ')"
