#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q53.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
node(){ command "${NODE:-node}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
node -e '' >/dev/null 2>&1 || invalid "no working node ($NODE=${NODE:-node})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests (trap-dense): quoted commas, escaped quotes, quoted NEWLINES
# (a field spanning lines), CRLF line endings, a trailing newline not making an extra
# row, a trailing empty field, and empty input.
cat > hidden_gate.mjs <<'JS'
import assert from "node:assert/strict";
import { parseCsv } from "./solution.mjs";

assert.deepEqual(parseCsv("a,b,c"), [["a", "b", "c"]], "simple");
assert.deepEqual(parseCsv("a,b\nc,d"), [["a", "b"], ["c", "d"]], "two rows");
assert.deepEqual(parseCsv('a,"b,c",d'), [["a", "b,c", "d"]], "quoted comma");
assert.deepEqual(parseCsv('"he said ""hi"""'), [['he said "hi"']], "escaped quote");
assert.deepEqual(parseCsv('a,"x\ny",b'), [["a", "x\ny", "b"]], "quoted newline");
assert.deepEqual(parseCsv("a,b\r\nc,d"), [["a", "b"], ["c", "d"]], "CRLF");
assert.deepEqual(parseCsv("a,b\nc,d\n"), [["a", "b"], ["c", "d"]], "trailing newline");
assert.deepEqual(parseCsv("a,b,"), [["a", "b", ""]], "trailing empty field");
assert.deepEqual(parseCsv(""), [], "empty input");
console.log("OK");
JS

out=$(node hidden_gate.mjs 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'AssertionError|Error|newline|CRLF' | head -4 | tr '\n' ' ')"
fi
pass "all hidden parseCsv tests passed"
