#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q24.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
pytest(){ command "${PYTEST:-pytest}" "$@"; }
python(){ command "${PYTHON:-python}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
pytest --version >/dev/null 2>&1 || invalid "no working pytest ($PYTEST=${PYTEST:-pytest})"
python --version >/dev/null 2>&1 || invalid "no working python ($PYTHON=${PYTHON:-python})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: greedy fill, an over-long word on its own line, exact-width
# fit, empty input, and whitespace normalization (collapse runs, trim, tabs) — a
# naive split(' ') approach fails the whitespace cases.
cat > hidden_gate_test.py <<'PY'
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from solution import word_wrap

def test_basic():
    assert word_wrap("the quick brown fox", 9) == "the quick\nbrown fox"

def test_long_word_own_line():
    assert word_wrap("a supercalifragilistic b", 5) == "a\nsupercalifragilistic\nb"

def test_exact_fit():
    assert word_wrap("ab cd", 5) == "ab cd"

def test_empty():
    assert word_wrap("", 10) == ""

def test_collapses_multiple_spaces():
    assert word_wrap("hello   world", 20) == "hello world"

def test_trims_and_handles_tabs():
    assert word_wrap("  a\tb  ", 20) == "a b"

def test_whitespace_only_is_empty():
    assert word_wrap("   \t  ", 10) == ""
PY

out=$(python -m pytest -q hidden_gate_test.py 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'assert|error|failed' | head -4 | tr '\n' ' ')"
fi
pass "all hidden word_wrap tests passed"
