#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q44.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: count-desc ordering, alphabetical tie-break, case folding,
# and mixed whitespace (tabs/newlines) as separators.
chk() { # <expected-multiline> <input>
  local exp got
  exp=$(printf '%b' "$1")
  got=$(printf '%b' "$2" | bash solution.sh 2>/dev/null)
  [ "$got" = "$exp" ] || fail "input $(printf '%q' "$2"): expected [$exp] got [$got]"
}
chk '3 the\n2 cat\n1 dog' 'the cat the DOG the cat'
chk '1 apple\n1 banana\n1 cherry' 'banana apple cherry'
chk '3 hi' 'Hi hi HI'
chk '3 a\n1 b' 'a\tb  a\na'
pass "frequency tally sorted, case-folded, whitespace-split"
