#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q19.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
pytest(){ command "${PYTEST:-pytest}" "$@"; }
python(){ command "${PYTHON:-python}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
pytest --version >/dev/null 2>&1 || invalid "no working pytest ($PYTEST=${PYTEST:-pytest})"
python --version >/dev/null 2>&1 || invalid "no working python ($PYTHON=${PYTHON:-python})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: the 1024 boundary, one-decimal rounding, and scaling all
# the way up through MB/GB/TB (not just KB).
cat > hidden_gate_test.py <<'PY'
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from solution import human_readable_size

def test_below_kb():
    assert human_readable_size(0) == "0 B"
    assert human_readable_size(1023) == "1023 B"

def test_kb_boundary():
    assert human_readable_size(1024) == "1.0 KB"
    assert human_readable_size(1536) == "1.5 KB"

def test_rounds_to_one_decimal():
    assert human_readable_size(1500) == "1.5 KB"

def test_scales_up():
    assert human_readable_size(1048576) == "1.0 MB"
    assert human_readable_size(1073741824) == "1.0 GB"
    assert human_readable_size(1099511627776) == "1.0 TB"
    assert human_readable_size(1125899906842624) == "1.0 PB"
PY

out=$(python -m pytest -q hidden_gate_test.py 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'assert|error|failed' | head -4 | tr '\n' ' ')"
fi
pass "all hidden size-format tests passed"
