// GENERATED by build_bcf_scorer.py. Do not edit.
// rule_score / detect_language_hint are a VERBATIM byte slice of
// D:\dev\battle-command-forge\src\router.rs  (sha256 5263aeaf878222ff2b8d41375651af2fe27ba248d6052599d9c449c4e7472293).
use std::io::Read;

fn rule_score(prompt: &str) -> u32 {
    let text = prompt.to_lowercase();
    let word_count = prompt.split_whitespace().count();
    let mut score: f64 = 1.0; // base score (matched to v2)

    // ── 1. STRUCTURAL COMPLEXITY ──

    // Count explicit steps
    let steps = text.matches("step ").count();
    if steps >= 7 {
        score += 3.0;
    } else if steps >= 5 {
        score += 2.0;
    } else if steps >= 3 {
        score += 1.0;
    }

    // Count file extensions mentioned
    let file_exts = [
        ".py", ".ts", ".js", ".tsx", ".jsx", ".json", ".css", ".html", ".go", ".php",
    ];
    let file_count: usize = file_exts.iter().filter(|ext| text.contains(*ext)).count();
    if file_count >= 3 {
        score += 2.0;
    } else if file_count >= 2 {
        score += 1.0;
    }

    // Count function/class definitions expected
    let def_keywords = ["function", "class", "def ", "interface", "struct"];
    let def_count: usize = def_keywords.iter().map(|k| text.matches(k).count()).sum();
    if def_count >= 3 {
        score += 1.0;
    }

    // ── 2. SEMANTIC COMPLEXITY (4-tier keywords, matched to v2) ──

    let trivial = [
        "simple",
        "basic",
        "single",
        "just",
        "only",
        "straightforward",
    ];
    let moderate = [
        "handle",
        "validate",
        "check",
        "multiple",
        "combine",
        "integrate",
        "parse",
        "convert",
        "transform",
        "edge case",
        "error handling",
    ];
    let high = [
        "refactor",
        "optimize",
        "async",
        "concurrent",
        "parallel",
        "nested",
        "recursive",
        "complex",
        "algorithm",
        "data structure",
        "database",
        "api",
        "service",
        "module",
        "component",
        "cache",
        "lru",
        "linked list",
        "hash map",
        "tree",
        "graph",
        "queue",
        "stack",
        "heap",
        "binary",
        "sorting",
        "searching",
        "o(1)",
        "o(n)",
        "o(log",
        "time complexity",
    ];
    let extreme = [
        "architect",
        "design system",
        "framework",
        "infrastructure",
        "distributed",
        "microservice",
        "migration",
        "legacy",
        "security",
        "authentication",
        "authorization",
        "real-time",
        "multiple files",
        "full application",
        "project",
    ];

    let mut max_tier: f64 = 0.0;

    let extreme_hits = extreme.iter().filter(|k| text.contains(*k)).count();
    if extreme_hits >= 2 {
        max_tier = max_tier.max(4.0);
    } else if extreme_hits == 1 {
        max_tier = max_tier.max(3.0);
    }

    let high_hits = high.iter().filter(|k| text.contains(*k)).count();
    if high_hits >= 3 {
        max_tier = max_tier.max(3.0);
    } else if high_hits >= 1 {
        max_tier = max_tier.max(2.0);
    }

    let mod_hits = moderate.iter().filter(|k| text.contains(*k)).count();
    if mod_hits >= 2 {
        max_tier = max_tier.max(2.0);
    } else if mod_hits >= 1 {
        max_tier = max_tier.max(1.0);
    }

    let trivial_hits = trivial.iter().filter(|k| text.contains(*k)).count();
    if trivial_hits >= 2 && max_tier <= 1.0 {
        score -= 0.5;
    }

    score += max_tier;

    // ── 3. LENGTH FACTOR ──
    if word_count > 100 {
        score += 2.0;
    } else if word_count > 50 {
        score += 1.0;
    } else if word_count < 10 {
        score -= 0.5;
    }

    // ── 4. LANGUAGE MODIFIER ──
    let lang = detect_language_hint(&text);
    match lang {
        "go" | "rust" => score += 0.5,
        "typescript" => score += 0.5,
        _ => {}
    }

    // Web project boost (HTML/CSS usually need more files/context)
    if text.contains("html") || text.contains("landing page") || text.contains("website") {
        score = score.max(7.0);
    }

    (score.round() as u32).clamp(1, 10)
}

fn detect_language_hint(lower: &str) -> &str {
    if lower.contains("rust") || lower.contains("cargo") {
        "rust"
    } else if lower.contains("golang") || lower.contains(" go ") {
        "go"
    } else if lower.contains("typescript") || lower.contains("next.js") {
        "typescript"
    } else {
        "python"
    }
}

fn main() {
    let mut s = String::new();
    std::io::stdin().read_to_string(&mut s).unwrap();
    // stdin is one prompt per record, records separated by a NUL byte.
    for rec in s.split('\u{0}') {
        if rec.is_empty() { continue; }
        let (id, text) = rec.split_once('\u{1}').unwrap_or(("?", rec));
        println!("{}\t{}", id, rule_score(text));
    }
}
