#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q51.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
pytest(){ command "${PYTEST:-pytest}" "$@"; }
python(){ command "${PYTHON:-python}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
pytest --version >/dev/null 2>&1 || invalid "no working pytest ($PYTEST=${PYTEST:-pytest})"
python --version >/dev/null 2>&1 || invalid "no working python ($PYTHON=${PYTHON:-python})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests (trap-dense): combined units, all three units, whitespace
# tolerance, order-independence, large values, and STRICT validation — an invalid
# or empty string, or one with stray characters, must raise ValueError (not guess).
cat > hidden_gate_test.py <<'PY'
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pytest
from solution import parse_duration

def test_combined_all_units():
    assert parse_duration("1h30m15s") == 5415

def test_single_units():
    assert parse_duration("2h") == 7200
    assert parse_duration("30m") == 1800
    assert parse_duration("45s") == 45

def test_whitespace_tolerated():
    assert parse_duration("1h 30m") == 5400

def test_order_independent():
    assert parse_duration("30m1h") == 5400

def test_large_value():
    assert parse_duration("100h") == 360000

def test_invalid_raises():
    with pytest.raises(ValueError):
        parse_duration("abc")

def test_empty_raises():
    with pytest.raises(ValueError):
        parse_duration("")

def test_stray_characters_raise():
    with pytest.raises(ValueError):
        parse_duration("1h2x")

def test_bare_number_raises():
    # no unit suffix -> not a valid duration
    with pytest.raises(ValueError):
        parse_duration("45")
PY

out=$(python -m pytest -q hidden_gate_test.py 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'assert|error|failed|raises' | head -4 | tr '\n' ' ')"
fi
pass "all hidden parse_duration tests passed"
