#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q14.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
pytest(){ command "${PYTEST:-pytest}" "$@"; }
python(){ command "${PYTHON:-python}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
pytest --version >/dev/null 2>&1 || invalid "no working pytest ($PYTEST=${PYTEST:-pytest})"
python --version >/dev/null 2>&1 || invalid "no working python ($PYTHON=${PYTHON:-python})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: recursive nested merge, scalar override, keys unique to
# each side preserved, and crucially neither input dict is mutated.
cat > hidden_gate_test.py <<'PY'
import os, sys, copy
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from solution import deep_merge

def test_scalar_override():
    assert deep_merge({"k": 1}, {"k": 2}) == {"k": 2}

def test_disjoint_keys_preserved():
    assert deep_merge({"a": 1}, {"b": 2}) == {"a": 1, "b": 2}

def test_nested_dicts_merge_recursively():
    a = {"cfg": {"x": 1, "y": 2}}
    b = {"cfg": {"y": 3, "z": 4}}
    assert deep_merge(a, b) == {"cfg": {"x": 1, "y": 3, "z": 4}}

def test_inputs_not_mutated():
    a = {"cfg": {"x": 1}}
    b = {"cfg": {"y": 2}}
    a0, b0 = copy.deepcopy(a), copy.deepcopy(b)
    deep_merge(a, b)
    assert a == a0, "first argument was mutated"
    assert b == b0, "second argument was mutated"

def test_dict_replaces_scalar():
    # b's value is a dict where a's is a scalar: b wins wholesale.
    assert deep_merge({"x": 1}, {"x": {"y": 2}}) == {"x": {"y": 2}}

def test_scalar_replaces_dict():
    # b's value is a scalar where a's is a dict: b wins wholesale.
    assert deep_merge({"x": {"y": 2}}, {"x": 5}) == {"x": 5}
PY

out=$(python -m pytest -q hidden_gate_test.py 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'assert|error|failed|mutated' | head -4 | tr '\n' ' ')"
fi
pass "all hidden deep_merge tests passed"
