//! Stage 4 — emit. Writes the task directory SPEC v1 describes.
//!
//! The TOML is written by hand rather than serialized, for the same reason `w8-import` and
//! `w8-import-q56` write theirs: a serializer strips comments, and the comments carry the
//! findings. SPEC §2 makes that the format's job, not a nicety.

use crate::donor::{DonorTask, Recorded};
use crate::gate::{FIXTURE_INIT, GateResult};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

/// SPEC §3's closed vocabulary. The three provenance lists must partition it exactly, and the
/// loader checks that (§13 rule 10). Read by the partition test, which is the only place
/// it can be checked before the loader sees the emitted tree.
#[cfg_attr(not(test), allow(dead_code))]
pub const FIELDS: [&str; 16] = [
    "id", "title", "lang", "kind", "timeout_s", "turn", "prompt", "fixture", "verify", "refsol",
    "sham", "variants", "disposition", "selection", "gate", "donor_tags",
];

const VERBATIM: [&str; 4] = ["prompt", "refsol", "timeout_s", "donor_tags"];
const REWRITTEN: [&str; 3] = ["id", "verify", "fixture"];
const SYNTHESIZED: [&str; 9] = [
    "title", "lang", "kind", "turn", "sham", "variants", "disposition", "selection", "gate",
];

fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out
}

fn list(items: &[&str]) -> String {
    let inner = items.iter().map(|s| format!("\"{s}\"")).collect::<Vec<_>>().join(", ");
    let one = format!("[{inner}]");
    if one.len() <= 84 {
        return one;
    }
    let mut out = String::from("[\n");
    let mut line = String::from("               ");
    for (i, s) in items.iter().enumerate() {
        let piece = format!("\"{s}\"{}", if i + 1 == items.len() { "" } else { ", " });
        if line.trim_start().chars().count() + piece.chars().count() > 80 {
            out.push_str(line.trim_end());
            out.push('\n');
            line = String::from("               ");
        }
        line.push_str(&piece);
    }
    out.push_str(line.trim_end());
    out.push_str("]");
    out
}

/// A word-wrapped triple-quoted caveat with TOML line continuations — the shape both other
/// importers use, so the three suites read the same.
fn caveat(text: &str, indent: usize) -> String {
    let pad = " ".repeat(indent);
    let width = 94usize.saturating_sub(indent);
    let mut lines: Vec<String> = Vec::new();
    let mut cur = String::new();
    for word in text.split_whitespace() {
        if !cur.is_empty() && cur.chars().count() + 1 + word.chars().count() > width {
            lines.push(std::mem::take(&mut cur));
        }
        if !cur.is_empty() {
            cur.push(' ');
        }
        cur.push_str(word);
    }
    if !cur.is_empty() {
        lines.push(cur);
    }
    let body = lines.iter().map(|l| format!("{pad}{l}")).collect::<Vec<_>>().join(" \\\n");
    format!("{pad}\"\"\"\n{body}\\\n{pad}\"\"\",\n")
}

fn caveats_block(items: &[String], indent: usize) -> String {
    let mut s = String::from("caveats = [\n");
    for (i, c) in items.iter().enumerate() {
        s.push_str(&caveat(c, indent));
        if i + 1 != items.len() {
            s.push('\n');
        }
    }
    s.push_str("]\n");
    s
}

/// Refuse to clobber anything this importer did not write. Generated files carry `# GENERATED by`
/// on line 1; `prompt.txt`, the fixture and the refsol cannot (their content is the donor's), so
/// they are guarded by `--force` alone.
fn write_guarded(path: &Path, body: &str, marked: bool, force: bool) -> Result<(), String> {
    if path.exists() {
        if !force {
            return Err(format!("{} exists; pass --force to replace it", path.display()));
        }
        if marked {
            let existing = fs::read_to_string(path).unwrap_or_default();
            // The marker sits in the header comment, which is line 1 of a task.toml and line 5 of
            // a verify.sh (below the shebang and the donor attribution). Eight lines covers both
            // and is still far too few to reach anything a human would have written.
            let marked_here =
                existing.lines().take(8).any(|l| l.contains("GENERATED by w8-import-u40"));
            if !marked_here {
                return Err(format!(
                    "{} was not written by w8-import-u40 (no `GENERATED by` marker); refusing \
                     to replace it even with --force",
                    path.display()
                ));
            }
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
    }
    fs::write(path, body).map_err(|e| format!("{}: {e}", path.display()))
}

pub struct EmitCtx<'a> {
    pub donor_commit: &'a str,
    pub donor_path: &'a str,
    pub imported_at: &'a str,
    pub force: bool,
    /// Recorded outcome per donor task name, keyed by the run's label.
    pub baselines: &'a BTreeMap<String, BTreeMap<String, Recorded>>,
}

fn kind_of(task: &DonorTask) -> &'static str {
    if task.symbols.iter().any(|s| s.starts_with(|c: char| c.is_uppercase())) {
        "class"
    } else {
        "function"
    }
}

pub fn task_dir(out: &Path, id: &str) -> std::path::PathBuf {
    out.join("suites").join("u40").join("tasks").join(id)
}

pub fn emit_task(
    out: &Path,
    task: &DonorTask,
    gate: &GateResult,
    verify_body: &str,
    ctx: &EmitCtx,
) -> Result<(), String> {
    let dir = task_dir(out, &task.id);

    // 1. The prompt — the donor's `description`, verbatim, and the reference solution nowhere
    //    near it.
    write_guarded(&dir.join("prompt.txt"), &format!("{}\n", task.description), false, ctx.force)?;

    // 2. The verifier.
    write_guarded(&dir.join("verify.sh"), verify_body, true, ctx.force)?;

    // 3. The fixture — the donor's own `tasks/__init__.py`, per task instead of once per campaign.
    write_guarded(&dir.join("fixture").join(FIXTURE_INIT), "", false, ctx.force)?;

    // 4. The answer key. The loader never hands this path to a runner.
    write_guarded(
        &dir.join("refsol").join(&task.artifact),
        &format!("{}\n", task.code),
        false,
        ctx.force,
    )?;

    // 5. task.toml
    let mut t = String::new();
    t.push_str(&format!(
        "# GENERATED by w8-import-u40 from agent-battle-command-center @ {}.\n\
         # Hand edits are fine, but re-running the importer over this directory will not\n\
         # overwrite it without --force: emit into a fresh tree and diff if you want to see\n\
         # what changed.\n\n",
        ctx.donor_commit
    ));
    t.push_str("schema    = 1\n");
    t.push_str(&format!("id        = \"{}\"\n", task.id));
    t.push_str(&format!(
        "title     = \"create {}\"   # mechanical; see [provenance].caveats\n",
        task.artifact
    ));
    t.push_str("lang      = \"python\"\n");
    t.push_str(&format!(
        "kind      = \"{}\"     # synthesized: the donor has no kind, only a complexity band\n",
        kind_of(task)
    ));
    t.push_str(
        "\n# The donor has no per-task timeout; its global TASK_TIMEOUT_MS is 5 minutes\n\
         # (ollama-stress-test-40.js:26). Carried verbatim.\n",
    );
    t.push_str("timeout_s = 300\n\n");
    t.push_str("[[turn]]\nsend_file = \"prompt.txt\"\n\n");
    t.push_str("[verify]\nkind   = \"script\"\nscript = \"verify.sh\"\n\n");

    // Disposition.
    let quarantined = gate.quarantine();
    t.push_str(
        "# ---------------------------------------------------------------------------\n\
         # Disposition — SPEC.md §10\n\
         # ---------------------------------------------------------------------------\n",
    );
    t.push_str("[disposition]\n");
    t.push_str("verifiable = \"full\"\n");
    t.push_str(&format!(
        "quarantine = \"{}\"\n",
        if quarantined { "with_baseline" } else { "none" }
    ));
    let reason = if quarantined {
        "a gate point came back `broken` at import: the verifier does not do what SPEC §9 \
         requires of it on this task. The standing rule for anything that fails the gate is \
         quarantine-with-baseline (David, 2026-08-08), so the task is imported and excluded from \
         aggregates rather than dropped — the evidence below is what a reader needs to decide \
         whether it can be repaired."
    } else {
        "the verifier executes the artifact and asserts its behaviour against the donor's own \
         examples, so a PASS establishes correctness on those inputs and not merely presence. \
         The gate ran all three tiers it can: absence and a null stub are both rejected, and the \
         donor's own reference solution is accepted."
    };
    t.push_str("reason = \"\"\"\n");
    t.push_str(&caveat(reason, 0).trim_start_matches("\"\"\"\n").trim_end_matches("\"\"\",\n"));
    t.push_str("\"\"\"\n\n");

    // Gate.
    t.push_str(
        "# ---------------------------------------------------------------------------\n\
         # Gate — SPEC.md §9. Recorded at import, not asserted at run time.\n\
         #\n\
         # Point 1 runs TWO pre-states, absence and a null-implementation stub: absence alone\n\
         # only proves the import machinery raised (F19). Point 2 is answerable here because\n\
         # the donor ships a reference solution in its `code` field — U100 had none and had to\n\
         # record `not_run`. Point 3 needs a plausible-but-wrong sham, which does not exist for\n\
         # this donor, so `[selection]` is absent and gate3 is false.\n\
         # ---------------------------------------------------------------------------\n",
    );
    t.push_str("[gate]\n");
    t.push_str(&format!("point1 = \"{}\"\n", gate.point1));
    t.push_str(&format!("point2 = \"{}\"\n", gate.point2));
    t.push_str(&format!("point3 = \"{}\"\n", gate.point3));
    for e in &gate.evidence {
        t.push_str("\n[[gate.evidence]]\n");
        t.push_str(&format!("point    = {}\n", e.point));
        t.push_str(&format!("tier     = \"{}\"\n", e.tier.name()));
        t.push_str(&format!("verdict  = \"{}\"\n", e.verdict.name()));
        t.push_str(&format!("detail   = \"{}\"\n", escape(&e.detail)));
        t.push_str("verifier = \"rewritten\"\n");
        t.push_str(&format!("run      = \"{}\"\n", escape(&gate.run)));
    }

    // Provenance.
    t.push_str(
        "\n# ---------------------------------------------------------------------------\n\
         # Provenance — every corpus field appears in exactly one of the three lists\n\
         # ---------------------------------------------------------------------------\n",
    );
    t.push_str("[provenance]\n");
    t.push_str("donor        = \"abcc-u40\"\n");
    t.push_str(&format!("donor_id     = \"{}\"\n", task.name));
    t.push_str(&format!("donor_commit = \"{}\"\n", ctx.donor_commit));
    t.push_str(&format!("donor_path   = \"{}\"\n", ctx.donor_path));
    t.push_str(&format!("imported_at  = \"{}\"\n\n", ctx.imported_at));
    t.push_str(&format!("verbatim    = {}\n", list(&VERBATIM)));
    t.push_str(&format!("rewritten   = {}\n", list(&REWRITTEN)));
    t.push_str(&format!("synthesized = {}\n\n", list(&SYNTHESIZED)));

    let mut caveats = vec![
        format!(
            "PROMPT IS VERBATIM, and it is the donor's `description` field — not the \
             `fullDescription` that createTask (:372-380) builds. That one interpolates \
             `task.code`, the reference solution, into the prompt text; it is posted to the task \
             DB record and never reaches the model, because executeTask (:412) sends \
             `task.description` and the agents service uses `request.task_description` verbatim \
             (packages/agents/src/main.py:325). This task's DB record would have named \
             `tasks/{}.py`{}.",
            task.db_stem,
            if task.db_stem == task.id {
                ", the same file".to_string()
            } else {
                format!(
                    " — a DIFFERENT file from the `{}` this prompt and this verifier both name, \
                     which is why the recorded run cannot have used it",
                    task.artifact
                )
            }
        ),
        "VERIFIER REWRITE, four ways, none of them touching an assertion: the docker exec \
         execution model is dropped for the runner's work dir; the interpreter resolves through \
         $PYTHON (SPEC §8); a missing interpreter is INVALID rather than the donor's catch-all \
         false; and the donor's own `result.includes('PASS')` contract is preserved by capturing \
         stdout, so a body that completes without printing PASS is a FAIL. The assertion body \
         itself is executed rather than reformatted."
            .to_string(),
        "FIXTURE: the donor's resetSystem (:362) runs `touch /app/workspace/tasks/__init__.py` \
         once per campaign, into ONE cumulative workspace shared by all 40 tasks. That file is \
         reproduced here per task, which is better science and breaks byte-comparability with \
         the recorded runs — a later task in the donor could import an earlier task's artifact, \
         and here it cannot."
            .to_string(),
    ];
    if task.db_stem != task.id {
        caveats.push(format!(
            "ID IS REWRITTEN, not verbatim: the donor's `name` is \"{}\" and its own file-naming \
             rule would give the stem `{}`, but the prompt and the verifier agree on `{}`. The \
             artifact path is the authority — the id follows what the verifier imports.",
            task.name, task.db_stem, task.id
        ));
    }
    t.push_str(&caveats_block(&caveats, 2));

    // Donor tags.
    t.push_str("\n[donor_tags]\n");
    t.push_str(&format!(
        "complexity = {}        # the donor's own 1-9 band; it drives the donor's context\n\
         \x20                     # routing (8K below C7, 16K at and above it), not a difficulty\n\
         \x20                     # ranking this corpus asserts\n",
        task.complexity
    ));
    t.push_str(&format!("name       = \"{}\"\n", task.name));
    t.push_str(&format!("db_stem    = \"{}\"\n", task.db_stem));
    t.push_str(&format!("artifact   = \"{}\"\n", task.artifact));
    t.push_str(&format!("symbols    = \"{}\"\n", task.symbols.join(",")));
    for (label, per_task) in ctx.baselines {
        if let Some(r) = per_task.get(&task.name) {
            t.push_str(&format!("{label:10} = \"{} in {}s\"\n", r.status, r.duration_s));
        }
    }

    write_guarded(&dir.join("task.toml"), &t, true, ctx.force)
}

pub fn emit_suite(
    out: &Path,
    tasks: &[DonorTask],
    ctx: &EmitCtx,
    caveats: &[String],
    force: bool,
) -> Result<(), String> {
    let dir = out.join("suites").join("u40");
    let mut s = String::new();
    s.push_str(&format!(
        "# GENERATED by w8-import-u40 from agent-battle-command-center @ {}.\n",
        ctx.donor_commit
    ));
    s.push_str("schema = 1\n");
    s.push_str("id     = \"u40\"\n");
    s.push_str(
        "title  = \"ABCC's 40-task Ollama stress battery — greenfield Python, C1-C9, \
         executable assertions\"\n\n",
    );
    s.push_str(
        "# Imported to close a §16 acceptance criterion honestly rather than by argument: the\n\
         # brief names this corpus, the set had never been imported, and `prestudy/\n\
         # data-assets.md:23` marks it \"Saturated\". §579 still rules that W8 starts from the\n\
         # 100-task suite as closer to 2.0's target workload — this suite does not displace it.\n\n",
    );
    s.push_str(
        "[aggregate]\n\
         # Identical to u100's and q56's rule, deliberately: three suites scored under one rule\n\
         # can be quoted in one sentence. `presence_only` is listed for that reason alone — no\n\
         # u40 task carries it, because every one of these verifiers executes the artifact.\n\
         include_verifiable  = [\"full\", \"presence_only\"]\n\
         exclude_quarantined = true\n\
         retry_on_timeout    = false\n\n",
    );
    s.push_str("[provenance]\n");
    s.push_str("donor        = \"abcc-u40\"\n");
    s.push_str(&format!("donor_commit = \"{}\"\n", ctx.donor_commit));
    s.push_str(&format!("donor_path   = \"{}\"\n", ctx.donor_path));
    s.push_str(&format!("imported_at  = \"{}\"\n\n", ctx.imported_at));
    s.push_str(&format!(
        "# The count is the boundary of this suite, not the directory listing: the importer\n\
         # aborts on any other count rather than importing whatever it found.\n\
         expected_tasks = {}\n\n",
        tasks.len()
    ));
    s.push_str(&caveats_block(caveats, 2));

    s.push_str(
        "\n# ---------------------------------------------------------------------------\n\
         # Default variants, inherited by every task in the suite. SPEC.md §5.\n\
         #\n\
         # ONE, and deliberately: this suite cannot measure operator control. All 40 tasks create\n\
         # a file that does not exist, and creating a new file never fires a permission gate\n\
         # whichever edit tool the model reaches for (F39) — which is exactly the gap Q56 was\n\
         # sourced to fill (F38, F40). A `gated` variant here would pass by construction and\n\
         # would describe the task genre rather than the subject.\n\
         # ---------------------------------------------------------------------------\n\n",
    );
    s.push_str(
        "# Donor-faithful: the recorded runs drove a CrewAI agent whose file_write tool had no\n\
         # permission prompt in front of it, so `allow` is what the baselines were measured under.\n\
         [[variant]]\n\
         id          = \"control\"\n\
         permissions = { mode = \"allow\" }\n\
         operator    = []\n",
    );

    if dir.join("suite.toml").exists() && !force {
        return Err(format!("{} exists; pass --force to replace it", dir.join("suite.toml").display()));
    }
    fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    write_guarded(&dir.join("suite.toml"), &s, true, true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_three_provenance_lists_partition_the_closed_vocabulary() {
        let mut all: Vec<&str> =
            VERBATIM.iter().chain(REWRITTEN.iter()).chain(SYNTHESIZED.iter()).copied().collect();
        all.sort_unstable();
        let mut want = FIELDS.to_vec();
        want.sort_unstable();
        assert_eq!(all, want, "rule 10 is checked at load; it must hold at emit");
    }
}
