//! `w8-import-u40` — imports ABCC's 40-task Ollama stress battery into a `corpus/SPEC.md` v1
//! corpus, closing the §16 acceptance criterion that names it.
//!
//! ```text
//! cargo run -p w8-import-u40 -- --out ../corpus
//! ```
//!
//! **A third path, deliberately, not a flag on `w8-import`.** That crate's `--donor` takes the
//! repo directory and `donor.rs` is hard-wired to `scripts/ultimate-100-task-test.js`, with a
//! byte-walker built for that file's multi-line template literals and its `BUGGY_FILES` map. This
//! donor has neither: one flat array, five string keys per object. Bending the 100-task walker
//! around a strictly simpler file would make both harder to read for no gain.
//!
//! The three rules the other two importers established, kept here:
//!
//! * **it never drops a task** — a task whose gate comes back `broken` is imported with
//!   `quarantine = "with_baseline"` (SPEC §10);
//! * **it never overwrites an authored file** — generated files carry `# GENERATED by` on line 1,
//!   and `--force` refuses anything without it;
//! * **it reads the donor and never writes to it** — through `git show`, so the donor cannot even
//!   be a working tree.

mod donor;
mod emit;
mod gate;
mod verify_sh;

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::process::ExitCode;

const DEFAULT_REPO: &str = r"D:\dev\agent-battle-command-center";
/// The same commit `w8-import` pinned for the 100-task donor. The `TASKS` array is byte-identical
/// at this commit, at the commit that produced the recorded 39/40 run, and at the commit before
/// the auto-retry pipeline landed — verified, so the tasks imported here are the tasks that ran.
const DEFAULT_COMMIT: &str = "d5528ea";
const DONOR_PATH: &str = "scripts/ollama-stress-test-40.js";
const RESULTS_PATH: &str = "scripts/ollama-stress-results-40.json";
/// The two recorded runs worth carrying per task: the last one (with the auto-retry pipeline in
/// front of it, 39/40) and the last one without it (36/40).
const BASELINES: [(&str, &str, &str); 2] = [
    ("recorded_after_retry", "01246c1", "2026-02-20, auto-retry pipeline in front of the agent"),
    ("recorded_single_try", "6c6bb86", "2026-02-18, one attempt per task"),
];
/// Held constant so re-running does not churn every `imported_at` in the corpus.
const DEFAULT_IMPORTED_AT: &str = "2026-08-26";
const EXPECTED_TASKS: usize = 40;

struct Args {
    repo: PathBuf,
    commit: String,
    out: PathBuf,
    only: Option<String>,
    force: bool,
    skip_gate: bool,
    imported_at: String,
}

fn main() -> ExitCode {
    let args = match parse_args() {
        Ok(a) => a,
        Err(m) => {
            eprintln!("{m}");
            return ExitCode::FAILURE;
        }
    };
    match run(args) {
        Ok(code) => code,
        Err(m) => {
            eprintln!("✗ {m}");
            ExitCode::FAILURE
        }
    }
}

fn usage() -> String {
    format!(
        "usage: w8-import-u40 --out <corpus-root> [--repo <dir>] [--commit <rev>] [--only <id>]\n\
         \x20                   [--force] [--skip-gate] [--imported-at <date>]\n\n\
         \x20 --out         corpus root; the suite is written to <out>/suites/u40/\n\
         \x20 --repo        donor repository (default: {DEFAULT_REPO})\n\
         \x20 --commit      donor revision, read with `git show` (default: {DEFAULT_COMMIT})\n\
         \x20 --only        emit one task by id, e.g. c5_flatten\n\
         \x20 --force       replace generated files; refuses anything without the marker\n\
         \x20 --skip-gate   emit with every gate point `not_run` (fast; not a corpus you can cite)\n"
    )
}

fn parse_args() -> Result<Args, String> {
    let mut a = Args {
        repo: PathBuf::from(DEFAULT_REPO),
        commit: DEFAULT_COMMIT.to_string(),
        out: PathBuf::new(),
        only: None,
        force: false,
        skip_gate: false,
        imported_at: DEFAULT_IMPORTED_AT.to_string(),
    };
    let mut it = std::env::args().skip(1);
    while let Some(arg) = it.next() {
        let mut next = |flag: &str| it.next().ok_or_else(|| format!("{flag} needs a value"));
        match arg.as_str() {
            "--out" => a.out = PathBuf::from(next("--out")?),
            "--repo" => a.repo = PathBuf::from(next("--repo")?),
            "--commit" => a.commit = next("--commit")?,
            "--only" => a.only = Some(next("--only")?),
            "--imported-at" => a.imported_at = next("--imported-at")?,
            "--force" => a.force = true,
            "--skip-gate" => a.skip_gate = true,
            "-h" | "--help" => return Err(usage()),
            other => return Err(format!("unknown argument {other:?}\n\n{}", usage())),
        }
    }
    if a.out.as_os_str().is_empty() {
        return Err(format!("--out is required\n\n{}", usage()));
    }
    Ok(a)
}

fn run(args: Args) -> Result<ExitCode, String> {
    let repo = args.repo.to_string_lossy().to_string();
    let src = donor::read_donor(&repo, &args.commit, DONOR_PATH)?;
    let tasks = donor::parse(&src, EXPECTED_TASKS)?;
    println!("✓ {} task objects at {}:{DONOR_PATH}", tasks.len(), args.commit);

    let disagreements = donor::path_disagreements(&tasks);
    println!(
        "  {} of {} tasks name a different file in the DB record than in the prompt — the \
         independent proof that the DB record's prompt never ran",
        disagreements.len(),
        tasks.len()
    );

    // The recorded baselines, per task, from two commits of the donor's own results file.
    let mut baselines: BTreeMap<String, BTreeMap<String, donor::Recorded>> = BTreeMap::new();
    for (label, commit, what) in BASELINES {
        let json = donor::read_donor(&repo, commit, RESULTS_PATH)?;
        let rows = donor::parse_results(&json)?;
        let passed = rows.iter().filter(|(_, r)| r.status == "passed").count();
        println!("  baseline {label}: {passed}/{} passed ({commit}, {what})", rows.len());
        baselines.insert(label.to_string(), rows.into_iter().collect());
    }

    let it = gate::Interpreters::resolve()?;
    let run_label = format!(
        "corpus/suites/u40/tasks/<id>/verify.sh, host, {} ({} + {})",
        args.imported_at, it.bash, it.python
    );

    let ctx = emit::EmitCtx {
        donor_commit: &args.commit,
        donor_path: DONOR_PATH,
        imported_at: &args.imported_at,
        force: args.force,
        baselines: &baselines,
    };

    let mut emitted = 0usize;
    let mut quarantined: Vec<&str> = Vec::new();
    let mut gate_rows: Vec<(String, String, String)> = Vec::new();
    for task in &tasks {
        if let Some(only) = &args.only
            && *only != task.id
        {
            continue;
        }
        let verify_body = verify_sh::render(task, &args.commit);
        let g = if args.skip_gate {
            gate::GateResult::not_run("not run: --skip-gate".to_string())
        } else {
            let scratch = std::env::temp_dir().join(format!("w8-import-u40-verify-{}.sh", task.id));
            std::fs::write(&scratch, &verify_body).map_err(|e| format!("{}: {e}", scratch.display()))?;
            let g = gate::run(&it, task, &scratch, &run_label);
            let _ = std::fs::remove_file(&scratch);
            g
        };
        if g.quarantine() {
            quarantined.push(&task.id);
        }
        gate_rows.push((task.id.clone(), g.point1.to_string(), g.point2.to_string()));
        emit::emit_task(&args.out, task, &g, &verify_body, &ctx)?;
        emitted += 1;
    }

    if args.only.is_none() {
        emit::emit_suite(&args.out, &tasks, &ctx, &suite_caveats(&disagreements), args.force)?;
    }

    println!("\n✓ emitted {emitted} task(s) into {}", emit::task_dir(&args.out, "").display());
    let sound1 = gate_rows.iter().filter(|(_, p, _)| p == "sound").count();
    let sound2 = gate_rows.iter().filter(|(_, _, p)| p == "sound").count();
    println!(
        "  gate point 1 (rejects absence AND a null stub): sound on {sound1}/{emitted}\n\
         \x20 gate point 2 (accepts the donor's own solution): sound on {sound2}/{emitted}"
    );
    if !quarantined.is_empty() {
        println!("  ⚠ quarantined with baseline: {}", quarantined.join(", "));
        for (id, p1, p2) in &gate_rows {
            if p1 != "sound" || p2 != "sound" {
                println!("      {id}: point1 = {p1}, point2 = {p2}");
            }
        }
    }
    Ok(ExitCode::SUCCESS)
}

fn suite_caveats(disagreements: &[&donor::DonorTask]) -> Vec<String> {
    vec![
        format!(
            "🚨 THE RECORDED 39/40 IS AN AFTER-RETRY NUMBER AND MUST NEVER BE QUOTED AS A \
             SINGLE-ATTEMPT BASELINE. `ollama-stress-results-40.json` at 01246c1 records 39/40, \
             and that commit is the one that ADDED the retry pipeline — its own message reads \
             \"auto-retry pipeline — 90% → 98% pass rate (39/40)\" and describes phase 0 \
             validate, phase 1 Ollama retry with the error in context, phase 2 Haiku escalation. \
             The same 40 tasks scored 36/40 on one attempt, three times, across two \
             configurations (27018b1 qwen2.5-coder:32k, f32b1ff and 6c6bb86 dynamic 8K/16K/32K), \
             and 35/40 on qwen2.5-coder:7b at 159512f. So the honest floor for a one-attempt run \
             is 36/40 = 90%, and 39/40 is what v1 reached with an escalation ladder whose top \
             rung is a cloud model — which zero cloud spend (David, 2026-08-07) forbids \
             reproducing here."
        ),
        format!(
            "🚨 THE PROMPT THE MODEL SAW WAS `description`, NOT the `fullDescription` that \
             createTask (:372-380) builds — and this is a fact about the donor's wiring, not a \
             choice this import made. `fullDescription` interpolates `task.code`, the reference \
             solution, into the prompt text and posts it to the task DB record; executeTask \
             (:412) sends `task.description` to the agents service, which uses \
             `request.task_description` verbatim (packages/agents/src/main.py:325). The proof is \
             independent of both call sites: {} of 40 tasks name a different file in the DB \
             record than the prompt and the verifier agree on ({}), so a run driven by \
             `fullDescription` would have failed at least those {} on the filename alone. The \
             recorded run failed one.",
            disagreements.len(),
            disagreements
                .iter()
                .take(3)
                .map(|t| format!("`{}` vs `{}`", t.db_stem, t.id))
                .collect::<Vec<_>>()
                .join(", "),
            disagreements.len()
        ),
        "🚨 ONE TASK HAS NEVER PASSED, IN ANY RECORDED CONFIGURATION. `flatten_list` \
         (`c5_flatten`) is a failure in all five recorded runs — 7b, 32k, dynamic, dynamic \
         again, and dynamic with the retry pipeline and Haiku escalation in front of it. Any \
         comparison that reads 39/40 or 36/40 as \"the model's ceiling\" is reading a corpus \
         with one member nothing has ever solved. Its gate evidence in this suite is the first \
         time the verifier has been run against a known-correct answer."
            .to_string(),
        "HELD CONSTANTS DIFFER FROM THE DONOR'S, on every axis. The recorded runs used Ollama \
         serving qwen2.5-coder with the donor's own context routing — 8K below complexity 7 and \
         16K at or above it (getOllamaModel, :404-409) — inside a CrewAI agent with \
         maxIterations 5, a 5-minute task timeout, a 3-second rest between tasks and an agent \
         reset every 3. W8 runs the champion at ctx 61440 through Claudette. Nothing about the \
         two numbers is comparable except the tasks and the assertions, which is exactly why \
         this import exists: the criterion asks whether the new base agent clears v1's floor on \
         v1's own tasks, not whether two stacks tie."
            .to_string(),
        "SHARED WORKSPACE vs PER-TASK ISOLATION. All 40 donor tasks ran in one cumulative \
         /app/workspace, cleaned once per campaign (`rm -f tasks/c*.py; touch \
         tasks/__init__.py`, :362) rather than once per task. So a donor task could import an \
         artifact an earlier task wrote, and every artifact was visible to every later prompt's \
         agent. Here each task gets a fresh work dir holding only `tasks/__init__.py`. Better \
         science, and it breaks byte-comparability with the recorded runs."
            .to_string(),
        "THE REFERENCE SOLUTION IS ON DISK, at `refsol/tasks/<id>.py`, carried verbatim from the \
         donor's `code` field. It is the gate's point-2 input and an answer key for a reader; \
         the loader never hands its path to a runner, and it must never be delivered to a \
         subject. It is also the reason this suite can answer gate point 2 at all."
            .to_string(),
        "VERIFIER TIMEOUT: the donor gave its validation 15 seconds (:608) and treated a timeout \
         as a failure. SPEC §8 gives the grader its own budget, set on the w8-run command line, \
         and a verifier that does not finish is INVALID rather than FAIL."
            .to_string(),
    ]
}
