//! Stage 2 — the verifier rewrite, and the one place this import touches donor code.
//!
//! Four changes, none of which may alter an assertion:
//!
//! 1. **The execution model is dropped.** The donor runs the assertion body as
//!    `docker exec -w /app/workspace abcc-agents python3 -c "import base64; exec(...)"`
//!    (`ollama-stress-test-40.js:601-616`). Here it runs in the work dir the runner made, with the
//!    work dir on `sys.path` — which is what `-w /app/workspace` bought the donor, since every
//!    validation is a `from tasks.<mod> import …`.
//! 2. **The interpreter resolves through the environment** (SPEC §8), so the same task runs on the
//!    host and in a container.
//! 3. **A missing interpreter prints `INVALID`, not `FAIL`.** The donor's `catch { return false }`
//!    (`:613-615`) makes "the verifier did not run" and "the artifact is wrong" the same fact.
//!    SPEC §8 has a third verdict for exactly this.
//! 4. **The donor's PASS contract is preserved rather than replaced.** The donor scores
//!    `result.includes('PASS')` on captured stdout — not "no exception" — so stdout is captured
//!    here too and a body that completes without printing `PASS` is a FAIL. Every one of the 40
//!    validations ends in `print('PASS')`, so the two rules agree today; keeping the donor's is
//!    what makes that agreement a fact rather than an assumption.
//!
//! The assertion body itself is **executed, not inlined**, inside a raw triple-quoted literal, so
//! reformatting can never become an unrecorded edit. `donor::parse` refuses any validation that
//! could not survive that literal.

use crate::donor::DonorTask;

pub fn render(task: &DonorTask, donor_commit: &str) -> String {
    format!(
        r##"#!/usr/bin/env bash
# Rewritten from ABCC's `validation` string for task `{name}`
# (scripts/ollama-stress-test-40.js, agent-battle-command-center @ {commit}).
#
# GENERATED by w8-import-u40. Every edit to the donor is recorded in this task's task.toml
# [provenance].caveats; the assertion body below is NOT edited.
#
# SPEC.md §8: invoked as `bash verify.sh <workdir> <transcript>`, writes exactly one RESULT: line
# to stdout, exit status ignored, both arguments absolute. Output with no RESULT: line is INVALID,
# never FAIL — "the verifier did not run" and "the artifact is wrong" are different facts, and the
# donor's `catch {{ return false }}` conflated them.
set -u

work="${{1:?usage: verify.sh <workdir> <transcript>}}"
: "${{2-}}"   # transcript, unused: this donor verifier reads only the artifact

interp="${{PYTHON:-python3}}"

# SPEC §8: probe by EXECUTING, not by looking. Windows' Store alias shim `python3.exe` is on PATH,
# resolves to `command -v`, and prints an advert instead of running code (exit 9009).
if ! "$interp" -c '' >/dev/null 2>&1; then
  echo "RESULT: INVALID interpreter '$interp' does not execute"
  exit 0
fi

cd "$work" || {{ echo "RESULT: INVALID workdir '$work' does not exist"; exit 0; }}

"$interp" - "$work" <<'PY'
import contextlib
import io
import sys

# What `docker exec -w /app/workspace` bought the donor: the work dir is the import root, so
# `from tasks.<mod> import …` resolves against the artifact the subject wrote.
sys.path.insert(0, sys.argv[1])

# The donor's `validation` string, verbatim. Artifact under test: {artifact}
DONOR = r'''
{validation}
'''

captured = io.StringIO()
try:
    with contextlib.redirect_stdout(captured):
        exec(compile(DONOR, "<donor-verifier>", "exec"), {{"__name__": "__donor__"}})
except Exception as e:
    msg = str(e)
    print(f"RESULT: FAIL {{type(e).__name__}}" + (f": {{msg}}" if msg else ""))
else:
    # The donor's own contract: `result.includes('PASS')` over captured stdout.
    if "PASS" in captured.getvalue():
        print("RESULT: PASS donor assertions held and the body printed PASS")
    else:
        print("RESULT: FAIL the donor body completed without printing PASS")
PY
"##,
        name = task.name,
        commit = donor_commit,
        artifact = task.artifact,
        validation = task.validation,
    )
}
