//! The `verify.sh` templates — SPEC §8's contract, wrapped around the donor's own assertions.
//!
//! Two templates, because the donor's two verifier families reject in genuinely different ways:
//!
//!   * **python** raises. An in-process `try/except` sees the rejection and can name it, which
//!     is what makes `detail = "AssertionError"` possible. This is the shape the worked example
//!     froze.
//!   * **node** rejects by calling `process.exit(1)` without throwing, and two of the seventeen
//!     end in `console.log('PASS'); else process.exit(1)` so the PASS print cannot even be
//!     stripped uniformly. An in-process `try/catch` would see nothing at all, so the donor's
//!     own contract — `exit 0 AND "PASS" in stdout` — is reproduced in the shell instead.
//!
//! Both templates execute the donor's assertion body **verbatim**. Reformatting it to read
//! nicely would be an edit that no provenance list records.

/// Guard against the three ways an embedded body could break the file it is written into.
/// All three were measured absent across the 80 donor verifiers before these templates were
/// written; the assertion is here so that a future donor commit fails loudly instead of
/// emitting shell that silently does something else.
fn assert_embeddable(name: &str, body: &str, heredoc: &str) {
    assert!(
        !body.contains("'''"),
        "task {name}: verifier body contains ''' and cannot be embedded in a raw python string"
    );
    assert!(
        !body.trim_end().ends_with('\\'),
        "task {name}: verifier body ends with a backslash, which would escape the raw string's \
         closing quotes"
    );
    assert!(
        !body.lines().any(|l| l.trim_end() == heredoc),
        "task {name}: verifier body contains a line equal to the heredoc marker {heredoc}"
    );
}

fn header(name: &str, interp: &str) -> String {
    format!(
        "#!/usr/bin/env bash\n\
         # Rewritten from ABCC's `validation` string for task `{name}`\n\
         # (scripts/ultimate-100-task-test.js, agent-battle-command-center @ d5528ea).\n\
         #\n\
         # Generated by harness/crates/w8-import. Every edit to the donor is recorded in this\n\
         # task's task.toml [provenance].caveats; the assertion body below is NOT edited.\n\
         #\n\
         # SPEC.md §8: invoked as `bash verify.sh <workdir> <transcript>`, writes exactly one\n\
         # RESULT: line to stdout, exit status ignored, both arguments absolute. Output with no\n\
         # RESULT: line is INVALID, never FAIL — \"the verifier did not run\" and \"the artifact is\n\
         # wrong\" are different facts and the donor conflated them (F8).\n\
         set -u\n\
         \n\
         work=\"${{1:?usage: verify.sh <workdir> <transcript>}}\"\n\
         : \"${{2-}}\"   # transcript, unused: this donor verifier reads only the artifact\n\
         \n\
         interp=\"${{{interp}}}\"\n"
    )
}

/// SPEC §8: probe by **executing**, not by looking. Windows ships a Microsoft Store alias shim
/// named `python3.exe`; it is on PATH, `command -v` finds it, and running it prints an advert
/// and exits 9009 instead of running the code. Measured on this host, so this is not a
/// hypothetical. A mis-resolved interpreter is INVALID, never FAIL.
fn probe(flag: &str) -> String {
    // The concrete example is python's, so only the python template gets to cite it.
    let why = if flag == "-c" {
        "# Windows' Store alias shim `python3.exe` is on PATH, resolves to `command -v`, and\n\
         # prints an advert instead of running code (measured on the import host: exit 9009).\n"
    } else {
        "# An interpreter that resolves but does not run is the failure this catches.\n"
    };
    format!(
        "# SPEC §8: probe by EXECUTING, not by looking.\n\
         {why}\
         # A mis-resolved interpreter is INVALID, never FAIL.\n\
         if ! \"$interp\" {flag} '' >/dev/null 2>&1; then\n  \
         echo \"RESULT: INVALID interpreter '$interp' does not execute\"\n  \
         exit 0\n\
         fi\n\
         \n\
         cd \"$work\" || {{ echo \"RESULT: INVALID workdir '$work' does not exist\"; exit 0; }}\n"
    )
}

/// The python template. `${PYTHON:-python3}`, so the same task runs on the host and in a
/// container.
pub fn python(name: &str, body: &str, artifact: &str) -> String {
    assert_embeddable(name, body, "PY");
    let mut s = header(name, "PYTHON:-python3");
    s.push('\n');
    s.push_str(&probe("-c"));

    if name == "fix_path_traversal" {
        s.push_str(
            "\n# TASK-SPECIFIC REWRITE: the donor probes a base dir of '/tmp' and reaches out of\n\
             # it for '../etc/passwd' — two absolute container paths. Both move inside the work\n\
             # dir, or the verifier measures the host filesystem instead of the artifact.\n\
             mkdir -p \"$work/base\" \"$work/etc\"\n\
             printf 'root:x:0:0:root:/root:/bin/sh\\n' > \"$work/etc/passwd\"\n",
        );
    }

    s.push_str(&format!(
        "\n\"$interp\" - \"$work\" <<'PY'\n\
         import sys\n\
         \n\
         sys.path.insert(0, sys.argv[1])\n\
         \n\
         # The donor's assertion body, verbatim apart from the rewrites recorded in task.toml:\n\
         # the /app/workspace sys.path insert, the dotted `tasks.<dir>.<mod>` import path, and\n\
         # the trailing print('PASS'). It is executed rather than inlined so that reformatting\n\
         # never becomes an unrecorded edit. Artifact under test: {artifact}\n\
         DONOR = r'''\n{body}\n'''\n\
         \n\
         try:\n    \
         exec(compile(DONOR, \"<donor-verifier>\", \"exec\"), {{\"__name__\": \"__donor__\"}})\n\
         except Exception as e:\n    \
         msg = str(e)\n    \
         print(f\"RESULT: FAIL {{type(e).__name__}}\" + (f\": {{msg}}\" if msg else \"\"))\n\
         else:\n    \
         print(\"RESULT: PASS donor assertions held\")\n\
         PY\n"
    ));
    s
}

/// The node template. The donor's verdict channel is reproduced in the shell rather than
/// replaced, because these verifiers reject with `process.exit(1)` rather than by throwing.
pub fn node(name: &str, body: &str) -> String {
    assert_embeddable(name, body, "JS");
    let mut s = header(name, "NODE:-node");
    s.push('\n');
    s.push_str(&probe("-e"));
    s.push_str(&format!(
        "\n# The donor scores `exit 0 AND \"PASS\" in stdout` (ultimate-100-task-test.js:2809 and\n\
         # packages/agents/src/main.py:524-589). That contract is reproduced here rather than\n\
         # replaced: these verifiers reject by calling process.exit(1) rather than by throwing,\n\
         # so an in-process try/catch would not see a rejection at all.\n\
         out=\"$(\"$interp\" - <<'JS' 2>&1\n{body}\nJS\n)\"\n\
         rc=$?\n\
         \n\
         if [ \"$rc\" -eq 0 ] && printf '%s\\n' \"$out\" | grep -q '^PASS$'; then\n  \
         echo \"RESULT: PASS donor assertions held\"\n  \
         exit 0\n\
         fi\n\
         \n\
         # The FIRST error line, not the last: node prints the error near the top and closes with\n\
         # a `Node.js vX` banner, so taking the last line reports a version string as the reason.\n\
         # The optional dotted prefix and the empty stem both matter — a bare `Error:` line is\n\
         # how node reports a missing module, and requiring a character before `Error` misses it.\n\
         detail=\"$(printf '%s\\n' \"$out\" \\\n  \
         | grep -m1 -E '^([A-Za-z_][A-Za-z0-9_.]*\\.)?[A-Za-z_]*(Error|Exception)\\b')\"\n\
         if [ -z \"$detail\" ]; then\n  \
         if [ \"$rc\" -ne 0 ]; then\n    \
         detail=\"exit $rc, no error line (the donor verifier's process.exit reject path)\"\n  \
         else\n    \
         detail=\"no PASS on stdout\"\n  \
         fi\n\
         fi\n\
         echo \"RESULT: FAIL $detail\"\n"
    ));
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn python_script_has_the_required_shape() {
        let s = python("demo", "from b import f; assert f()", "b.py");
        assert!(s.starts_with("#!/usr/bin/env bash\n"));
        assert!(s.contains("${PYTHON:-python3}"));
        assert!(s.contains("RESULT: INVALID"));
        assert!(s.contains("from b import f; assert f()"));
        assert!(s.contains("RESULT: PASS donor assertions held"));
        assert!(s.contains("<<'PY'") && s.trim_end().ends_with("PY"));
    }

    #[test]
    fn node_script_scores_the_donor_contract() {
        let s = node("demo", "var u=require('./b'); console.log('PASS')");
        assert!(s.contains("${NODE:-node}"));
        assert!(s.contains("<<'JS'"));
        assert!(s.contains("grep -q '^PASS$'"));
        assert!(s.contains("process.exit reject path"));
    }

    #[test]
    fn fix_path_traversal_gets_its_containment_setup() {
        let s = python("fix_path_traversal", "r=read_file('base','../etc/passwd')", "x.py");
        assert!(s.contains("mkdir -p \"$work/base\" \"$work/etc\""));
        assert!(s.contains("etc/passwd"));
        // and no other task does
        let other = python("fix_sql_inject", "r=get_user(None,'x')", "x.py");
        assert!(!other.contains("mkdir -p"));
    }

    #[test]
    #[should_panic(expected = "cannot be embedded")]
    fn refuses_a_body_that_would_break_the_raw_string() {
        python("bad", "x = '''oops'''", "x.py");
    }

    #[test]
    #[should_panic(expected = "heredoc marker")]
    fn refuses_a_body_that_would_close_the_heredoc() {
        node("bad", "var a=1;\nJS\nvar b=2;");
    }
}
