#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q08.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
cargo(){ command "${CARGO:-cargo}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
cargo --version >/dev/null 2>&1 || invalid "no working cargo ($CARGO=${CARGO:-cargo})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: left-associative chained subtraction, with precedence
# and mixed operators still intact.
mkdir -p tests
cat > tests/hidden_gate.rs <<'RS'
use q08::evaluate;
#[test] fn precedence() { assert_eq!(evaluate("2 + 3 * 4"), 14); }
#[test] fn single_subtraction() { assert_eq!(evaluate("10 - 3"), 7); }
#[test] fn chained_subtraction() { assert_eq!(evaluate("10 - 3 - 2"), 5); }
#[test] fn long_subtraction_chain() { assert_eq!(evaluate("100 - 10 - 5 - 1"), 84); }
#[test] fn mixed_precedence_and_sub() { assert_eq!(evaluate("20 - 2 * 3 - 4"), 10); }
#[test] fn all_subtraction() { assert_eq!(evaluate("50 - 20 - 10 - 5"), 15); }
RS

out=$(cargo test --test hidden_gate --quiet 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'panicked|assertion|error\[|FAILED' | head -4 | tr '\n' ' ')"
fi
echo "$out" | grep -qE 'test result: ok' \
  && pass "all hidden evaluator tests passed" \
  || fail "no green result: $(echo "$out" | tail -3 | tr '\n' ' ')"
