#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q49.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer test: leading AND trailing whitespace stripped (incl. tabs),
# internal spaces preserved, blank line stays blank.
input=$(printf '  hello  \n\tworld\t\nclean\n\n  a  b  ')
expected=$(printf 'hello\nworld\nclean\n\na  b')

got=$(printf '%s\n' "$input" | bash solution.sh 2>/dev/null)
[ "$got" = "$expected" ] || fail "expected [$expected] got [$got]"
pass "normalize strips both ends, keeps internal spacing"
