#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q07.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
cargo(){ command "${CARGO:-cargo}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
cargo --version >/dev/null 2>&1 || invalid "no working cargo ($CARGO=${CARGO:-cargo})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: deterministic count-desc / alphabetical ordering,
# case folding, punctuation as separators, and the empty case.
mkdir -p tests
cat > tests/hidden_gate.rs <<'RS'
use q07::word_frequencies;
#[test] fn most_frequent_first() {
    let f = word_frequencies("the cat sat on the mat the");
    assert_eq!(f[0], ("the".to_string(), 3));
}
#[test] fn case_insensitive() {
    assert_eq!(word_frequencies("The THE the"), vec![("the".to_string(), 3)]);
}
#[test] fn splits_on_punctuation_and_newlines() {
    assert_eq!(word_frequencies("hi,\thi.\nhi!"), vec![("hi".to_string(), 3)]);
}
#[test] fn ties_broken_alphabetically() {
    assert_eq!(
        word_frequencies("cherry banana apple"),
        vec![("apple".to_string(), 1), ("banana".to_string(), 1), ("cherry".to_string(), 1)]
    );
}
#[test] fn empty_text() {
    assert_eq!(word_frequencies(""), Vec::<(String, usize)>::new());
}
RS

out=$(cargo test --test hidden_gate --quiet 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'panicked|assertion|error\[|FAILED' | head -4 | tr '\n' ' ')"
fi
echo "$out" | grep -qE 'test result: ok' \
  && pass "all 5 hidden word_frequencies tests passed" \
  || fail "no green result: $(echo "$out" | tail -3 | tr '\n' ' ')"
