#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q46.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

cd "$WORKDIR" || fail "cannot cd into workdir"

# Ten numbered lines "1".."10".
INPUT=$(printf '%s\n' 1 2 3 4 5 6 7 8 9 10)

chk() { # <expected-multiline> <start> <end>
  local exp got
  exp=$(printf '%b' "$1")
  got=$(printf '%s\n' "$INPUT" | bash solution.sh "$2" "$3" 2>/dev/null)
  [ "$got" = "$exp" ] || fail "range $2..$3: expected [$exp] got [$got]"
}
chk '3\n4\n5' 3 5      # mid range
chk '4' 4 4            # single line
chk '1\n2' 1 2         # from start
chk '8\n9\n10' 8 100   # end beyond EOF
chk '' 20 30           # start beyond EOF
chk '' 5 3             # start after end -> empty (degenerate range)
pass "inclusive line range correct including edges"
