#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q02.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
cargo(){ command "${CARGO:-cargo}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
cargo --version >/dev/null 2>&1 || invalid "no working cargo ($CARGO=${CARGO:-cargo})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: empty slice, out-of-range on both ends, duplicates
# (must return the LEFTMOST equal position), and a present single value.
mkdir -p tests
cat > tests/hidden_gate.rs <<'RS'
use q02::lower_bound;
#[test] fn example() { assert_eq!(lower_bound(&[1,2,4,5], 3), 2); }
#[test] fn empty_slice() { assert_eq!(lower_bound(&[], 5), 0); }
#[test] fn below_all() { assert_eq!(lower_bound(&[5,6,7], 1), 0); }
#[test] fn above_all() { assert_eq!(lower_bound(&[1,2,3], 10), 3); }
#[test] fn leftmost_of_duplicates() { assert_eq!(lower_bound(&[1,2,2,2,3], 2), 1); }
#[test] fn present_value() { assert_eq!(lower_bound(&[1,3,5], 3), 1); }
#[test] fn all_equal_leftmost() { assert_eq!(lower_bound(&[2,2,2,2], 2), 0); }
#[test] fn all_equal_above() { assert_eq!(lower_bound(&[2,2,2], 5), 3); }
RS

out=$(cargo test --test hidden_gate --quiet 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'panicked|assertion|error\[|FAILED' | head -4 | tr '\n' ' ')"
fi
echo "$out" | grep -qE 'test result: ok' \
  && pass "all 6 hidden lower_bound tests passed" \
  || fail "no green result: $(echo "$out" | tail -3 | tr '\n' ' ')"
