#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q47.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

cd "$WORKDIR" || fail "cannot cd into workdir"

# Normal division to stdout, integer truncation, negatives.
got=$(bash solution.sh 10 2 2>/dev/null); [ "$got" = "5" ] || fail "10/2 expected 5 got '$got'"
got=$(bash solution.sh 7 2 2>/dev/null);  [ "$got" = "3" ] || fail "7/2 expected 3 got '$got'"
got=$(bash solution.sh -6 3 2>/dev/null); [ "$got" = "-2" ] || fail "-6/3 expected -2 got '$got'"

# Division by zero: non-zero exit, and NOTHING on stdout.
out=$(bash solution.sh 5 0 2>/dev/null); rc=$?
[ "$rc" -ne 0 ] || fail "divide-by-zero should exit non-zero (got rc=0)"
[ -z "$out" ] || fail "divide-by-zero should print nothing to stdout (got '$out')"

pass "divides correctly and handles zero divisor cleanly"
