#!/usr/bin/env bash
# Rewritten from ABCC's `validation` string for task `stack_class`
# (scripts/ollama-stress-test-40.js, agent-battle-command-center @ d5528ea).
#
# GENERATED by w8-import-u40. Every edit to the donor is recorded in this task's task.toml
# [provenance].caveats; the assertion body below is NOT edited.
#
# SPEC.md §8: invoked as `bash verify.sh <workdir> <transcript>`, writes exactly one RESULT: line
# to stdout, exit status ignored, both arguments absolute. Output with no RESULT: line is INVALID,
# never FAIL — "the verifier did not run" and "the artifact is wrong" are different facts, and the
# donor's `catch { return false }` conflated them.
set -u

work="${1:?usage: verify.sh <workdir> <transcript>}"
: "${2-}"   # transcript, unused: this donor verifier reads only the artifact

interp="${PYTHON:-python3}"

# SPEC §8: probe by EXECUTING, not by looking. Windows' Store alias shim `python3.exe` is on PATH,
# resolves to `command -v`, and prints an advert instead of running code (exit 9009).
if ! "$interp" -c '' >/dev/null 2>&1; then
  echo "RESULT: INVALID interpreter '$interp' does not execute"
  exit 0
fi

cd "$work" || { echo "RESULT: INVALID workdir '$work' does not exist"; exit 0; }

"$interp" - "$work" <<'PY'
import contextlib
import io
import sys

# What `docker exec -w /app/workspace` bought the donor: the work dir is the import root, so
# `from tasks.<mod> import …` resolves against the artifact the subject wrote.
sys.path.insert(0, sys.argv[1])

# The donor's `validation` string, verbatim. Artifact under test: tasks/c9_stack.py
DONOR = r'''
from tasks.c9_stack import Stack; s=Stack(); assert s.is_empty()==True; s.push(1); s.push(2); assert s.peek()==2; assert s.size()==2; assert s.pop()==2; assert s.pop()==1; assert s.pop() is None; print('PASS')
'''

captured = io.StringIO()
try:
    with contextlib.redirect_stdout(captured):
        exec(compile(DONOR, "<donor-verifier>", "exec"), {"__name__": "__donor__"})
except Exception as e:
    msg = str(e)
    print(f"RESULT: FAIL {type(e).__name__}" + (f": {msg}" if msg else ""))
else:
    # The donor's own contract: `result.includes('PASS')` over captured stdout.
    if "PASS" in captured.getvalue():
        print("RESULT: PASS donor assertions held and the body printed PASS")
    else:
        print("RESULT: FAIL the donor body completed without printing PASS")
PY
