"""The deterministic half, scored against wrong answers instead of against time.

Item 3's F266 asked whether a generated acceptance criterion is red before the
change and green after it. This asks the question item 4 needs: **does it tell a
right answer from a wrong one?** — which is SPEC.md §9's point 3, the one the
K-suite says can only be closed by an authored sham:

    gate(task) := verify(pre_state) == FAIL
               && verify(fixture + refsol) == PASS
               && verify(fixture + sham) == FAIL

    "Point 1 bounds the defect rate from below. Only an authored sham closes it."

At runtime nobody has an authored sham. But three of this item's four artifacts
ARE shams, one of them generated by the model itself (`comment`), and all 35
criteria item 3 collected are on disk. Running them against each other costs
seconds and needs no GPU.

Reported per criterion: green on `refsol` (does it accept the right answer at
all), and green on each of `sham`, `comment`, `disable` (does it accept a wrong
one). A criterion is *discriminating* only if it is green on the first and red on
all three.
"""

import json
import pathlib
import shutil
import tempfile

import common as C

CRITERIA = json.loads(
    (C.HERE.parent / "w11-artifacts/criterion-results.json").read_text("utf-8")
)
OUT = C.HERE / "criteria-vs-shams.json"
SUBJECTS = ["refsol", "sham", "comment", "disable"]


def tree(aid):
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="w11cvs-"))
    return tmp, C.materialise(C.ARTIFACT_BY_ID[aid], tmp)


def main():
    trees = {}
    for aid in SUBJECTS:
        trees[aid] = tree(aid)

    # A runner that cannot tell exit 0 from exit 1 classifies everything the
    # same way; item 3 lost two runs to that. Prove it here, in this tree.
    _, work = trees["refsol"]
    assert C.bash("exit 0", work)[0] == 0 and C.bash("exit 5", work)[0] == 5
    assert C.bash("python3 -c 'print(1)'", work)[0] == 0
    assert C.bash(C.CRITERION, work)[0] == 0, "the item-4 criterion is green on refsol"

    rows = []
    for i, c in enumerate(CRITERIA, 1):
        cmd, cwd_rel = c["command"], c.get("cwd") or "."
        res = {}
        for aid in SUBJECTS:
            _, work = trees[aid]
            code, out = C.bash(cmd, work / cwd_rel if cwd_rel != "." else work)
            res[aid] = code
        accepts_wrong = [a for a in ("sham", "comment", "disable") if res[a] == 0]
        discriminating = res["refsol"] == 0 and not accepts_wrong
        rows.append(
            {
                "n": i,
                "command": cmd,
                "item3_class": c["final"],
                "exits": res,
                "green_on_refsol": res["refsol"] == 0,
                "accepts_wrong": accepts_wrong,
                "discriminating": discriminating,
            }
        )
        print(
            f"{i:2d} refsol={'green' if res['refsol'] == 0 else 'red  '} "
            f"sham={'green' if res['sham'] == 0 else 'red  '} "
            f"comment={'green' if res['comment'] == 0 else 'red  '} "
            f"disable={'green' if res['disable'] == 0 else 'red  '} "
            f"{'DISCRIMINATES' if discriminating else ''} {cmd[:70]}"
        )

    for tmp, _ in trees.values():
        shutil.rmtree(tmp, ignore_errors=True)

    n = len(rows)
    green = sum(1 for r in rows if r["green_on_refsol"])
    disc = sum(1 for r in rows if r["discriminating"])
    print(f"\n{green}/{n} accept the reference solution")
    print(f"{disc}/{n} accept the reference solution AND reject all three wrong answers")
    for a in ("sham", "comment", "disable"):
        k = sum(1 for r in rows if a in r["accepts_wrong"])
        print(f"{k}/{n} accept `{a}`")
    OUT.write_text(json.dumps(rows, indent=2), encoding="utf-8")
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
