#!/usr/bin/env bash
# Rewritten from ABCC's `validation` string for task `py_data_validator`
# (scripts/ultimate-100-task-test.js, agent-battle-command-center @ d5528ea).
#
# Generated by harness/crates/w8-import. Every edit to the donor is recorded in this
# task's task.toml [provenance].caveats; the assertion body below is NOT edited.
#
# SPEC.md §8: invoked as `bash verify.sh <workdir> <transcript>`, writes exactly one
# RESULT: line to stdout, exit status ignored, both arguments absolute. Output with no
# RESULT: line is INVALID, never FAIL — "the verifier did not run" and "the artifact is
# wrong" are different facts and the donor conflated them (F8).
set -u

work="${1:?usage: verify.sh <workdir> <transcript>}"
: "${2-}"   # transcript, unused: this donor verifier reads only the artifact

interp="${PYTHON:-python3}"

# SPEC §8: probe by EXECUTING, not by looking.
# Windows' Store alias shim `python3.exe` is on PATH, resolves to `command -v`, and
# prints an advert instead of running code (measured on the import host: exit 9009).
# A mis-resolved interpreter is INVALID, never FAIL.
if ! "$interp" -c '' >/dev/null 2>&1; then
  echo "RESULT: INVALID interpreter '$interp' does not execute"
  exit 0
fi

cd "$work" || { echo "RESULT: INVALID workdir '$work' does not exist"; exit 0; }

"$interp" - "$work" <<'PY'
import sys

sys.path.insert(0, sys.argv[1])

# The donor's assertion body, verbatim apart from the rewrites recorded in task.toml:
# the /app/workspace sys.path insert, the dotted `tasks.<dir>.<mod>` import path, and
# the trailing print('PASS'). It is executed rather than inlined so that reformatting
# never becomes an unrecorded edit. Artifact under test: schema_validator.py
DONOR = r'''
from schema_validator import Schema; s=Schema().required('name').string('name').required('age').number('age'); r=s.validate({'name':'Alice','age':30}); assert r['valid']==True; r2=s.validate({}); assert r2['valid']==False; assert len(r2['errors'])>=2; r3=s.validate({'name':123,'age':'bad'}); assert r3['valid']==False
'''

try:
    exec(compile(DONOR, "<donor-verifier>", "exec"), {"__name__": "__donor__"})
except Exception as e:
    msg = str(e)
    print(f"RESULT: FAIL {type(e).__name__}" + (f": {msg}" if msg else ""))
else:
    print("RESULT: PASS donor assertions held")
PY
