//! `w8-import-q56` — imports Claudette's Q56 quality battery into a `corpus/SPEC.md` v1 corpus.
//!
//! Step 5 of the W8 plan, and the critical path since David answered F38 with *front-load donor 2*.
//! U100 keeps its ~14 gate-capable tasks; this suite carries operator control, because **every one
//! of its 56 tasks ships a non-empty fixture** and touching a file that already exists always fires
//! a permission gate whichever edit tool the model reaches for (F39, F40).
//!
//! ```text
//! cargo run -p w8-import-q56 -- --repo D:/dev/claudette --out ../corpus
//! ```
//!
//! Design notes live in `README.md` and the survey in `research/W8-q56-import.md`; neither is
//! repeated here. The three rules the U100 importer established and this one keeps:
//!
//! * **it never drops a task** — a task failing a gate point is imported with
//!   `quarantine = "with_baseline"` (SPEC §10);
//! * **it never overwrites an authored file** — generated files carry `# GENERATED by` on line 1,
//!   and `--force` refuses anything without it;
//! * **it reads the donor and never writes to it** — here through `git show`, so the donor cannot
//!   even be a working tree.

mod donor;
mod emit;
mod gate;
mod verify_sh;

use std::path::{Path, PathBuf};
use std::process::ExitCode;

const DEFAULT_REPO: &str = r"D:\dev\claudette";
const DEFAULT_COMMIT: &str = "43d6b34";
const DEFAULT_BASE: &str = "runs/eval-2026-05-29/battery";
/// Held constant so re-running does not churn every `imported_at` in the corpus.
const DEFAULT_IMPORTED_AT: &str = "2026-08-08";
const EXPECTED_TASKS: usize = 56;

struct Args {
    repo: PathBuf,
    commit: String,
    base: String,
    out: PathBuf,
    only: Option<String>,
    force: bool,
    skip_gate: bool,
    imported_at: String,
}

fn main() -> ExitCode {
    let args = match parse_args() {
        Ok(a) => a,
        Err(m) => {
            eprintln!("{m}");
            return ExitCode::FAILURE;
        }
    };
    match run(args) {
        Ok(c) => c,
        Err(m) => {
            eprintln!("✗ {m}");
            ExitCode::FAILURE
        }
    }
}

fn parse_args() -> Result<Args, String> {
    let mut a = Args {
        repo: PathBuf::from(DEFAULT_REPO),
        commit: DEFAULT_COMMIT.to_string(),
        base: DEFAULT_BASE.to_string(),
        out: PathBuf::from("../corpus"),
        only: None,
        force: false,
        skip_gate: false,
        imported_at: DEFAULT_IMPORTED_AT.to_string(),
    };
    let mut it = std::env::args().skip(1);
    while let Some(arg) = it.next() {
        let mut next = |n: &str| it.next().ok_or_else(|| format!("{n} needs a value"));
        match arg.as_str() {
            "--repo" => a.repo = PathBuf::from(next("--repo")?),
            "--commit" => a.commit = next("--commit")?,
            "--base" => a.base = next("--base")?,
            "--out" => a.out = PathBuf::from(next("--out")?),
            "--only" => a.only = Some(next("--only")?),
            "--imported-at" => a.imported_at = next("--imported-at")?,
            "--force" => a.force = true,
            "--skip-gate" => a.skip_gate = true,
            "-h" | "--help" => {
                println!("{}", usage());
                std::process::exit(0);
            }
            other => return Err(format!("unknown argument {other}\n\n{}", usage())),
        }
    }
    Ok(a)
}

fn usage() -> &'static str {
    "usage: w8-import-q56 [--repo <claudette>] [--commit <sha>] [--base <path>]\n\
     \x20      [--out <corpus>] [--only <id>] [--imported-at <date>] [--force] [--skip-gate]\n\
     \n\
     The donor is read with `git show <commit>:<base>/...`, never from a working tree — naming an\n\
     exact commit is what makes the import reproducible, and it means a dirty checkout cannot leak\n\
     into the corpus. --skip-gate emits without measuring points 1 and 2, which is for iterating on\n\
     the emitter only: it writes `not_run`, and a corpus full of not_run gates establishes nothing."
}

fn run(args: Args) -> Result<ExitCode, String> {
    let d = donor::Donor::new(&args.repo, &args.commit, &args.base);
    let rows = d.manifest()?;
    println!("manifest: {} task(s) at {}:{}", rows.len(), args.commit, args.base);
    if rows.len() != EXPECTED_TASKS {
        return Err(format!(
            "the manifest holds {} rows, not {EXPECTED_TASKS}. The manifest is the boundary of this \
             suite, so a changed count means the donor moved and the import needs re-reading, not \
             re-running",
            rows.len()
        ));
    }

    let suite_dir = args.out.join("suites/q56");
    if !suite_dir.join("suite.toml").is_file() {
        return Err(format!(
            "no suite.toml at {}. It is authored, not generated — it carries the suite caveats, \
             the aggregate rule and the four variants",
            suite_dir.display()
        ));
    }

    let bash = if args.skip_gate { String::new() } else { gate::find_bash()? };
    let scratch = std::env::temp_dir().join("w8-import-q56");
    std::fs::create_dir_all(&scratch).map_err(|e| format!("{}: {e}", scratch.display()))?;

    let (mut ok, mut quarantined, mut skipped) = (0usize, 0usize, Vec::new());
    for row in &rows {
        if let Some(only) = &args.only
            && only != &row.id
        {
            continue;
        }
        let lang = match donor::spec_lang(&row.lang) {
            Ok(l) => l,
            Err(e) => {
                // Refused by name with the reason rather than mapped onto the nearest thing that
                // loads — a false value in a checkable field is worse than a missing task. F47's
                // eight shell tasks no longer land here: SPEC amendment 8 gave them a name. What
                // remains is a donor language nobody has mapped, which must stop and be looked at.
                skipped.push(format!("{}: {e}", row.id));
                continue;
            }
        };
        let task = d.task(row)?;
        let verify = verify_sh::rewrite(&row.id, &args.commit, &task.verify);

        let g = if args.skip_gate {
            gate::GateResult::not_run()
        } else {
            gate::run(&bash, &scratch, &task, &verify, &args.imported_at)?
        };

        let dir = suite_dir.join("tasks").join(&row.id);
        write_task(&dir, &task, lang, &verify, &g, &args)?;

        if g.holds() || args.skip_gate {
            ok += 1;
        } else {
            quarantined += 1;
        }
        println!(
            "  {:<5} {:<11} point1={:<12} point2={}",
            row.id,
            lang,
            g.point1.as_str(),
            g.point2.as_str()
        );
    }

    println!("\n{ok} clean, {quarantined} quarantined-with-baseline, {} skipped", skipped.len());
    for s in &skipped {
        println!("  ! {s}");
    }
    let emitted = ok + quarantined;
    if emitted == EXPECTED_TASKS {
        println!(
            "\nAll {EXPECTED_TASKS} emitted — set `expected_tasks = {EXPECTED_TASKS}` in \
             suites/q56/suite.toml now. It is deliberately absent while the suite is partial, \
             because the loader checks it against the tree and a rejected suite rejects the whole \
             corpus, u100 included."
        );
    } else {
        println!(
            "\n{emitted} of {EXPECTED_TASKS} on disk — leave `expected_tasks` OUT of \
             suites/q56/suite.toml until the set is complete."
        );
    }
    Ok(ExitCode::SUCCESS)
}

fn write_task(
    dir: &Path,
    task: &donor::DonorTask,
    lang: &str,
    verify: &str,
    g: &gate::GateResult,
    args: &Args,
) -> Result<(), String> {
    // The guard that exists because a --force run once clobbered the hand-authored worked example
    // and it had to come back out of git. A generated file says so on line 1; anything else is
    // authored and is never overwritten, --force or not.
    let toml_path = dir.join("task.toml");
    if toml_path.is_file() {
        let existing = std::fs::read_to_string(&toml_path).unwrap_or_default();
        let generated = existing.lines().next().is_some_and(|l| l.contains("GENERATED by"));
        if !generated {
            return Err(format!(
                "{} is authored (no `# GENERATED by` on line 1) and will not be overwritten. \
                 Move it aside if the generated one should replace it",
                toml_path.display()
            ));
        }
        if !args.force {
            return Err(format!("{} exists; pass --force to regenerate", toml_path.display()));
        }
    }

    std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    std::fs::write(dir.join("prompt.txt"), &task.prompt)
        .map_err(|e| format!("prompt.txt: {e}"))?;
    std::fs::write(dir.join("verify.sh"), verify).map_err(|e| format!("verify.sh: {e}"))?;
    emit::write_files(&dir.join("fixture"), &task.fixture)?;
    if !task.refsol.is_empty() {
        emit::write_files(&dir.join("refsol"), &task.refsol)?;
    }
    std::fs::write(
        &toml_path,
        emit::task_toml(task, lang, g, &args.imported_at, &args.commit),
    )
    .map_err(|e| format!("task.toml: {e}"))?;
    Ok(())
}
