//! Stage 2 — the verifier rewrite, and the one place this import touches donor code.
//!
//! Three changes, none of which may alter an assertion:
//!
//! 1. **`_lib.sh` is inlined.** A W8 task directory is self-contained (SPEC §2). Only the four
//!    lines Q56 uses are carried; `tc` / `tcre` / `tcount` are dropped as dead code, because no Q56
//!    verifier reads the transcript (F41).
//! 2. **Interpreters resolve through the environment** (SPEC §8), so the same task runs on the host
//!    and in a container.
//! 3. **A missing toolchain prints `INVALID`, not `FAIL`.** The donor harness fails such a task,
//!    which conflates "the verifier did not run" with "the artifact is wrong" and silently costs up
//!    to 19 points on a box without go/rust/node. This is F35's lesson and the reason SPEC §8 has a
//!    third verdict the donor contract does not.
//!
//! **Rule 2 is implemented with shell functions, not with a search-and-replace over call sites.**
//! Rewriting the text of `cargo test ...` into `"$CARGO" test ...` would have to distinguish a real
//! invocation from the same word inside a heredoc — and the heredocs here are the hidden reviewer
//! tests, the most load-bearing bytes in the whole donor. A function named `cargo` intercepts every
//! execution and touches no text at all, so the donor body below the prelude stays byte-identical.

/// The interpreters a Q56 verifier can reach for, and the env var that overrides each.
const INTERPRETERS: [(&str, &str); 4] =
    [("cargo", "CARGO"), ("pytest", "PYTEST"), ("python", "PYTHON"), ("node", "NODE")];

/// Which of them this script actually invokes. Word-boundary matched at the start of a command
/// position is more than this needs to be: an unused probe would only ever cost a false INVALID, so
/// the test is deliberately "does the word appear at all", which over-probes rather than under-.
pub fn interpreters_used(body: &str) -> Vec<(&'static str, &'static str)> {
    INTERPRETERS
        .iter()
        .copied()
        .filter(|(name, _)| {
            body.split(|c: char| !c.is_ascii_alphanumeric() && c != '_').any(|w| w == *name)
        })
        .collect()
}

/// Strip the donor's two-line header. Everything after it is carried verbatim.
///
/// **The two-line shape is measured across all 56, not assumed** (2026-08-08, `git show` over
/// `battery/q50-quality-corpus:runs/eval-2026-05-29/battery/verify/Q*.sh`): line 1 is the shebang,
/// line 2 is the `source`, and `_lib.sh` appears on no other line of any script. So the leading
/// `skip_while` cannot swallow an assertion, and no `source` survives further down to be resolved
/// against some *other* `_lib.sh` at run time.
fn body_after_header(donor: &str) -> String {
    donor
        .lines()
        .skip_while(|l| {
            let t = l.trim();
            t.starts_with("#!") || t.starts_with("source ") || t.is_empty()
        })
        .collect::<Vec<_>>()
        .join("\n")
}

pub fn rewrite(id: &str, donor_commit: &str, donor: &str) -> String {
    let used = interpreters_used(donor);
    let mut s = String::new();

    s.push_str("#!/usr/bin/env bash\n");
    s.push_str(&format!(
        "# GENERATED by w8-import-q56 from Claudette Q56 `verify/{id}.sh` \
         (battery/q50-quality-corpus @ {donor_commit}).\n"
    ));
    s.push_str(
        "#\n\
         # Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the\n\
         # tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through\n\
         # the environment as shell functions so the donor body stays byte-identical (SPEC §8); and\n\
         # a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below\n\
         # the prelude is the donor's, verbatim.\n\n",
    );

    s.push_str("WORKDIR=\"${1:?workdir}\"; TRANSCRIPT=\"${2:?transcript}\"\n");
    s.push_str("pass(){ echo \"RESULT: PASS — ${1:-ok}\"; exit 0; }\n");
    s.push_str("fail(){ echo \"RESULT: FAIL — ${1:-no reason}\"; exit 0; }\n");
    s.push_str(
        "invalid(){ echo \"RESULT: INVALID — ${1:-the verifier could not run}\"; exit 0; }\n\n",
    );

    if !used.is_empty() {
        s.push_str(
            "# `command` bypasses these functions, so this dispatches rather than recursing.\n",
        );
        for (name, var) in &used {
            s.push_str(&format!(
                "{name}(){{ command \"${{{var}:-{name}}}\" \"$@\"; }}\n"
            ));
        }
        s.push('\n');
        s.push_str(
            "# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named\n\
             # python3.exe that is on PATH, that `command -v` finds, and that prints an advert\n\
             # instead of running code (F27). A name resolving is not a working interpreter.\n",
        );
        for (name, var) in &used {
            let probe = match *name {
                "python" | "pytest" => format!("{name} --version"),
                "node" => "node -e ''".to_string(),
                _ => format!("{name} --version"),
            };
            s.push_str(&format!(
                "{probe} >/dev/null 2>&1 || invalid \"no working {name} \
                 (${var}=${{{var}:-{name}}})\"\n"
            ));
        }
        s.push('\n');
    }

    s.push_str(&body_after_header(donor));
    if !s.ends_with('\n') {
        s.push('\n');
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    const DONOR: &str = "#!/usr/bin/env bash\n\
                         source \"$(dirname \"$0\")/_lib.sh\"\n\
                         cd \"$WORKDIR\" || fail \"cannot cd into workdir\"\n\
                         out=$(cargo test --test hidden_gate --quiet 2>&1)\n\
                         pass \"ok\"\n";

    #[test]
    fn the_donor_body_survives_byte_for_byte() {
        let out = rewrite("Q08", "43d6b34", DONOR);
        assert!(out.contains("cd \"$WORKDIR\" || fail \"cannot cd into workdir\""));
        assert!(out.contains("out=$(cargo test --test hidden_gate --quiet 2>&1)"));
        // The header is replaced, not kept: a `source _lib.sh` that survived would break at run
        // time in a task dir that has no _lib.sh, and it would break loudly, which is the good
        // case. The bad case is it resolving to some *other* _lib.sh, so assert it is gone.
        //
        // Scoped to executable lines. The prelude's own comment says "_lib.sh inlined" — it is the
        // record of the rewrite and belongs in the output, so a blanket `!contains` would fail on
        // the documentation while a surviving `source` slipped past a differently-worded one.
        let live: Vec<&str> =
            out.lines().filter(|l| !l.trim_start().starts_with('#') && !l.trim().is_empty()).collect();
        assert!(
            live.iter().all(|l| !l.contains("_lib.sh")),
            "an executable line still references _lib.sh: {live:?}"
        );
    }

    #[test]
    fn only_the_interpreters_a_script_uses_are_probed() {
        let out = rewrite("Q08", "43d6b34", DONOR);
        assert!(out.contains("cargo(){ command \"${CARGO:-cargo}\" \"$@\"; }"));
        assert!(!out.contains("NODE"), "a rust task must not probe node");
        assert!(!out.contains("PYTEST"));
    }

    #[test]
    fn a_missing_toolchain_is_invalid_and_not_fail() {
        let out = rewrite("Q08", "43d6b34", DONOR);
        assert!(out.contains("RESULT: INVALID"));
        assert!(out.contains("|| invalid \"no working cargo"));
    }

    #[test]
    fn interpreters_are_detected_by_word_and_not_by_substring() {
        // `cargo_cult` must not look like `cargo`, or every task would probe every toolchain and a
        // box missing one would report INVALID for tasks that never needed it.
        let used = interpreters_used("echo cargo_cult; node -e ''");
        assert_eq!(used.iter().map(|(n, _)| *n).collect::<Vec<_>>(), vec!["node"]);
    }
}
