#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q25.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
pytest(){ command "${PYTEST:-pytest}" "$@"; }
python(){ command "${PYTHON:-python}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
pytest --version >/dev/null 2>&1 || invalid "no working pytest ($PYTEST=${PYTEST:-pytest})"
python --version >/dev/null 2>&1 || invalid "no working python ($PYTHON=${PYTHON:-python})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: exact cent totals including the classic float traps
# (4.35 -> 435, 19.99 -> 1999), plus sub-dollar and empty cases.
cat > hidden_gate_test.py <<'PY'
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from solution import total_cents

def test_whole_dollars():
    assert total_cents(["1.00", "2.00"]) == 300

def test_float_trap_435():
    assert total_cents(["4.35"]) == 435

def test_float_trap_1999():
    assert total_cents(["19.99"]) == 1999

def test_sub_dollar():
    assert total_cents(["0.10", "0.20", "0.05"]) == 35

def test_mixed_list():
    assert total_cents(["4.35", "19.99", "0.01"]) == 2435

def test_empty():
    assert total_cents([]) == 0

def test_integer_dollar_string():
    # a price with no decimal point still means whole dollars
    assert total_cents(["5"]) == 500
    assert total_cents(["5", "0.99"]) == 599
PY

out=$(python -m pytest -q hidden_gate_test.py 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'assert|error|failed' | head -4 | tr '\n' ' ')"
fi
pass "cent totals are exact"
