#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q22.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
pytest(){ command "${PYTEST:-pytest}" "$@"; }
python(){ command "${PYTHON:-python}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
pytest --version >/dev/null 2>&1 || invalid "no working pytest ($PYTEST=${PYTEST:-pytest})"
python --version >/dev/null 2>&1 || invalid "no working python ($PYTHON=${PYTHON:-python})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer test: 8 threads x 5000 increments must total exactly 40000.
# The unlocked read-modify-write loses updates under contention.
cat > hidden_gate_test.py <<'PY'
import os, sys, threading
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from solution import Counter

def test_concurrent_increments_not_lost():
    c = Counter()
    def worker():
        for _ in range(5000):
            c.increment()
    threads = [threading.Thread(target=worker) for _ in range(8)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert c.get() == 8 * 5000

def test_single_thread():
    c = Counter()
    for _ in range(100):
        c.increment()
    assert c.get() == 100
PY

out=$(python -m pytest -q hidden_gate_test.py 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'assert|error|failed' | head -4 | tr '\n' ' ')"
fi
pass "concurrent increments not lost"
