#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q41.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
node(){ command "${NODE:-node}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
node -e '' >/dev/null 2>&1 || invalid "no working node ($NODE=${NODE:-node})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: correctness (first repeat by second-occurrence, none, empty,
# immediate) plus a large all-distinct input that only a ~linear approach finishes fast.
cat > hidden_gate.ts <<'TS'
import assert from "node:assert/strict";
import { firstDuplicate } from "./solution.ts";

assert.strictEqual(firstDuplicate([1, 2, 3, 2, 1]), 2, "first repeat");
assert.strictEqual(firstDuplicate([1, 2, 3]), null, "no duplicate");
assert.strictEqual(firstDuplicate([]), null, "empty");
assert.strictEqual(firstDuplicate([5, 5]), 5, "immediate dup");
assert.strictEqual(firstDuplicate([3, 1, 4, 1, 5]), 1, "first by 2nd occurrence");

const n = 80000;
const distinct = Array.from({ length: n }, (_, i) => i);
const t = performance.now();
const got = firstDuplicate(distinct);
const elapsed = performance.now() - t;
assert.strictEqual(got, null, "all distinct -> null");
assert.ok(elapsed < 1500, `too slow: ${elapsed.toFixed(0)}ms (needs a linear approach)`);
console.log("OK");
TS

out=$(node hidden_gate.ts 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'AssertionError|too slow|Error' | head -4 | tr '\n' ' ')"
fi
pass "correct and fast on large input"
