#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q09.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
cargo(){ command "${CARGO:-cargo}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
cargo --version >/dev/null 2>&1 || invalid "no working cargo ($CARGO=${CARGO:-cargo})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: the boundary trap is multi-digit run counts (>9). A
# decoder that reads a single digit, or an encoder that can't emit "a12", breaks
# the round-trip. Also singletons ("a" -> "a1") and the empty string.
mkdir -p tests
cat > tests/hidden_gate.rs <<'RS'
use q09::{rle_decode, rle_encode};
#[test] fn encode_basic() { assert_eq!(rle_encode("aaabb"), "a3b2"); }
#[test] fn decode_basic() { assert_eq!(rle_decode("a3b2"), "aaabb"); }
#[test] fn singletons() { assert_eq!(rle_encode("abc"), "a1b1c1"); }
#[test] fn encode_multi_digit() { assert_eq!(rle_encode(&"a".repeat(12)), "a12"); }
#[test] fn decode_multi_digit() { assert_eq!(rle_decode("a12"), "a".repeat(12)); }
#[test] fn round_trip_long_run() {
    let s = format!("{}{}{}", "x".repeat(15), "y".repeat(3), "z".repeat(100));
    assert_eq!(rle_decode(&rle_encode(&s)), s);
}
#[test] fn empty() { assert_eq!(rle_encode(""), ""); assert_eq!(rle_decode(""), ""); }
RS

out=$(cargo test --test hidden_gate --quiet 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'panicked|assertion|error\[|FAILED' | head -4 | tr '\n' ' ')"
fi
echo "$out" | grep -qE 'test result: ok' \
  && pass "all hidden RLE tests passed" \
  || fail "no green result: $(echo "$out" | tail -3 | tr '\n' ' ')"
