#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q03.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
cargo(){ command "${CARGO:-cargo}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
cargo --version >/dev/null 2>&1 || invalid "no working cargo ($CARGO=${CARGO:-cargo})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: the remainder must be distributed (shares sum to total
# and differ by at most 1), plus the degenerate people==0 case must not panic.
mkdir -p tests
cat > tests/hidden_gate.rs <<'RS'
use q03::split_bill;
fn sum(v: &[u64]) -> u64 { v.iter().sum() }
#[test] fn even() { assert_eq!(split_bill(100, 4), vec![25,25,25,25]); }
#[test] fn remainder_sums_exact_1() { let v = split_bill(100, 3); assert_eq!(sum(&v), 100); assert_eq!(v.len(), 3); assert!(v.iter().max().unwrap() - v.iter().min().unwrap() <= 1); }
#[test] fn remainder_sums_exact_2() { let v = split_bill(10, 4); assert_eq!(sum(&v), 10); assert_eq!(v.len(), 4); assert!(v.iter().max().unwrap() - v.iter().min().unwrap() <= 1); }
#[test] fn single_person_gets_all() { assert_eq!(split_bill(5, 1), vec![5]); }
#[test] fn zero_total() { assert_eq!(split_bill(0, 3), vec![0,0,0]); }
#[test] fn zero_people_no_panic() { assert_eq!(split_bill(7, 0), Vec::<u64>::new()); }
RS

out=$(cargo test --test hidden_gate --quiet 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'panicked|assertion|error\[|FAILED|overflow' | head -4 | tr '\n' ' ')"
fi
echo "$out" | grep -qE 'test result: ok' \
  && pass "all 6 hidden split_bill tests passed" \
  || fail "no green result: $(echo "$out" | tail -3 | tr '\n' ' ')"
