#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q20.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
pytest(){ command "${PYTEST:-pytest}" "$@"; }
python(){ command "${PYTHON:-python}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
pytest --version >/dev/null 2>&1 || invalid "no working pytest ($PYTEST=${PYTEST:-pytest})"
python --version >/dev/null 2>&1 || invalid "no working python ($PYTHON=${PYTHON:-python})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: "present" means "not None" — falsy-but-real values like
# 0, "", and False must be KEPT (a plain `if v:` truthiness check wrongly drops them).
cat > hidden_gate_test.py <<'PY'
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from solution import keep_present

def test_drops_none_only():
    assert keep_present([1, None, 3, None]) == [1, 3]

def test_keeps_zero():
    assert keep_present([0, 1, 2]) == [0, 1, 2]

def test_keeps_empty_string():
    assert keep_present(["", "a"]) == ["", "a"]

def test_keeps_false():
    assert keep_present([False, True]) == [False, True]

def test_mixed_falsy_and_none():
    assert keep_present([0, None, "", None, 5]) == [0, "", 5]
PY

out=$(python -m pytest -q hidden_gate_test.py 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'assert|error|failed' | head -4 | tr '\n' ' ')"
fi
pass "keeps falsy-but-present values, drops only None"
