#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q54.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

# `command` bypasses these functions, so this dispatches rather than recursing.
pytest(){ command "${PYTEST:-pytest}" "$@"; }
python(){ command "${PYTHON:-python}" "$@"; }
node(){ command "${NODE:-node}" "$@"; }

# Probe by EXECUTING, never by looking: Windows ships a Store alias shim named
# python3.exe that is on PATH, that `command -v` finds, and that prints an advert
# instead of running code (F27). A name resolving is not a working interpreter.
pytest --version >/dev/null 2>&1 || invalid "no working pytest ($PYTEST=${PYTEST:-pytest})"
python --version >/dev/null 2>&1 || invalid "no working python ($PYTHON=${PYTHON:-python})"
node -e '' >/dev/null 2>&1 || invalid "no working node ($NODE=${NODE:-node})"

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests (trap-dense): valid order, deterministic alphabetical
# tie-break, cycle -> None, self-loop -> None, disconnected nodes included,
# empty graph -> [], and a node that only appears as a dependency is included.
cat > hidden_gate_test.py <<'PY'
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from solution import topological_sort

def test_linear():
    assert topological_sort({"b": ["a"], "c": ["b"]}) == ["a", "b", "c"]

def test_diamond_tie_break():
    assert topological_sort({"b": ["a"], "c": ["a"], "d": ["b", "c"]}) == ["a", "b", "c", "d"]

def test_cycle_returns_none():
    assert topological_sort({"a": ["b"], "b": ["a"]}) is None

def test_self_loop_is_cycle():
    assert topological_sort({"a": ["a"]}) is None

def test_disconnected_nodes_included_sorted():
    assert topological_sort({"a": [], "c": [], "b": []}) == ["a", "b", "c"]

def test_empty_graph():
    assert topological_sort({}) == []

def test_dependency_only_node_included():
    assert topological_sort({"y": ["x"]}) == ["x", "y"]
PY

out=$(python -m pytest -q hidden_gate_test.py 2>&1)
if [ $? -ne 0 ]; then
  fail "hidden tests failed: $(echo "$out" | grep -iE 'assert|error|failed|None' | head -4 | tr '\n' ' ')"
fi
pass "all hidden topological_sort tests passed"
