#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q43.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: trailing newline, NO trailing newline, single unterminated
# line, and empty input.
chk() { # <expected> <printf-arg>
  local exp="$1" in="$2" got
  got=$(printf '%b' "$in" | bash solution.sh 2>/dev/null)
  [ "$got" = "$exp" ] || fail "input $(printf '%q' "$in"): expected $exp, got '$got'"
}
chk 3 'a\nb\nc\n'
chk 3 'a\nb\nc'
chk 1 'x'
chk 0 ''
pass "line counts correct with and without trailing newline"
