#!/usr/bin/env bash
# GENERATED by w8-import-q56 from Claudette Q56 `verify/Q50.sh` (battery/q50-quality-corpus @ 43d6b34).
#
# Three rewrites, none of them touching an assertion: _lib.sh inlined (SPEC §2, and the
# tc/tcre/tcount transcript helpers dropped as dead — F41); interpreters resolved through
# the environment as shell functions so the donor body stays byte-identical (SPEC §8); and
# a missing toolchain printing INVALID rather than FAIL (SPEC §8, F35). Everything below
# the prelude is the donor's, verbatim.

WORKDIR="${1:?workdir}"; TRANSCRIPT="${2:?transcript}"
pass(){ echo "RESULT: PASS — ${1:-ok}"; exit 0; }
fail(){ echo "RESULT: FAIL — ${1:-no reason}"; exit 0; }
invalid(){ echo "RESULT: INVALID — ${1:-the verifier could not run}"; exit 0; }

cd "$WORKDIR" || fail "cannot cd into workdir"

# Hidden reviewer tests: comma-split field extraction, first field, missing field
# (fewer columns) -> empty, empty field -> empty, and multi-line.
chk() { # <expected-multiline> <col> <input>
  local exp got
  exp=$(printf '%b' "$1")
  got=$(printf '%b' "$3" | bash solution.sh "$2" 2>/dev/null)
  [ "$got" = "$exp" ] || fail "col $2 on $(printf '%q' "$3"): expected [$exp] got [$got]"
}
chk 'b' 2 'a,b,c\n'
chk 'a' 1 'a,b,c\n'
chk '' 5 'a,b\n'
chk '' 2 'a,,c\n'
chk 'z\n3' 3 'x,y,z\n1,2,3\n'
pass "extracts Nth comma field, handles missing/empty fields"
